/**
 * End-to-end deferred/incomplete implementation-round recovery
 * (plan Part 1, step 4): drives the REAL `runImplementationWithAI` →
 * `executeImplementationRun` path with only the provider boundary
 * (`runImplementationOrSealedV1`) and the extension-host seams faked — the
 * same require-cache monkey-patch harness completeAndMoveOnFastForward.test.ts
 * uses — and asserts the full recovery contract:
 *
 *   - a detected round leaves impl-summary.md, impl-summary_prev.md, and the
 *     review artifact's CONTENT byte-identical;
 *   - the review is flagged invalid via the durable metadata marker, not a
 *     placeholder write;
 *   - the round's delta lands in `pendingImplReviewFiles` and never in
 *     `implReviewFiles`, and is durable BEFORE the run log is written
 *     (crash-order invariant);
 *   - a continuation implementation round is scheduled (chainId
 *     "impl-continuation") instead of auto-advance/review dispatch;
 *   - an EMPTY completed response is the limiting case of the same contract
 *     (review blocker, 2026-08-13: it used to fall onto the rejected-summary
 *     path and bank its files);
 *   - a later successful round's prompt carries the Continuation Notice, its
 *     progress patch promotes the pending set (union with its own delta),
 *     and the review-invalid marker is cleared only after replacement
 *     review-tracking state has persisted (asserted across every persisted
 *     state, not just the final one);
 *   - the continuation cap escalates to human — pausing the task — even at
 *     an implementation stage where `reviewAttemptId` is legitimately absent.
 */
import * as assert from "node:assert/strict";
import * as cp from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { describe, it } from "node:test";
import * as vscode from "vscode";

import { runImplementationWithAI } from "../commands/reviewActions";
import {
  initNotificationRouter,
  deactivateNotificationRouter,
} from "../utils/notificationRouter";
import { StatusTreeProvider } from "../views/statusView";
import { decodeTaskProgressTextV1 } from "../services/taskProgressDecoderV1";
import {
  MAX_INCOMPLETE_ROUND_CONTINUATIONS_V1,
  TaskProgress,
} from "../types/taskProgress";
import { IncompleteTask } from "../types/incompleteTask";
import { DISCLAIMER_VERSION } from "../legal/disclaimerVersion";
import type { AutomationDispatch } from "../utils/automationChain";

/* eslint-disable @typescript-eslint/no-var-requires */
const runEditActionModule = require("../commands/runEditActionV1") as Record<string, unknown>;
const modelSelectionModule = require("../utils/modelSelection") as Record<string, unknown>;
const runnerRegistryModule = require("../runners/runnerRegistry") as Record<string, unknown>;
const contextPackModule = require("../utils/contextPack") as Record<string, unknown>;
const promptTemplatesModule = require("../utils/promptTemplates") as Record<string, unknown>;
const promptSizeGuardModule = require("../utils/promptSizeGuard") as Record<string, unknown>;
const automationChainModule = require("../utils/automationChain") as Record<string, unknown>;
const settingsModule = require("../config/settings") as Record<string, unknown>;
const runLogModule = require("../utils/runLog") as Record<string, unknown>;
const progressWriterModule = require("../services/taskProgressWriterV1") as Record<string, unknown>;
/* eslint-enable @typescript-eslint/no-var-requires */

const REAL_ROOT = fs.mkdtempSync(path.join(os.tmpdir(), "ensemble-deferred-round-"));
// Hermetic git scope: the OS temp dir can itself sit inside a git work tree
// (e.g. a dotfiles repo at the user's home directory), in which case the
// pre-run safety check's `git status` walks that ENTIRE tree — observed at
// 75s on a real machine, timing out every test here. A repo at the harness
// root pins rev-parse/status to this tiny directory instead.
cp.execFileSync("git", ["init", "-q"], { cwd: REAL_ROOT, windowsHide: true });

/** The observed round-014 shape: a deferral to a wakeup that never fires. */
const DEFERRED_RESPONSE =
  "All edits are staged. Waiting for the background test run to finish " +
  "(scheduled wakeup in ~5 min). I'll pick back up automatically when it " +
  "completes or the wakeup fires.";

const PLAN_FINAL = [
  "<!-- Generated by Test -->",
  "",
  "<!-- ensemble:implementation-checklist -->",
  "",
  "# Implementation Checklist",
  "",
  "- [ ] Add the resolver",
  "- [ ] Wire the decoder",
  "",
].join("\n");

/** A summary that passes the shape gate: echo + own Files Changed + Verification. */
const GOOD_SUMMARY = [
  "<!-- ensemble:implementation-checklist -->",
  "",
  "- [x] Add the resolver",
  "- [ ] Wire the decoder",
  "",
  "## Files Changed",
  "",
  "- `src/resolver.ts` — added the resolver",
  "",
  "## Verification",
  "",
  "- ran the unit tests",
].join("\n");

const PRIOR_SUMMARY = "# Prior Round Summary\n\nGood notes from the last usable round.\n";
const PRIOR_SUMMARY_PREV = "# Even Older Summary\n";
const PRIOR_REVIEW =
  "# Implementation Review\n\nReadiness: 6/10\n\nReal review content that must be preserved.\n";

interface FakeRunResult {
  status: "completed" | "failed" | "cancelled";
  filesChanged: string[];
  filesChangedUnknown?: boolean;
  summary?: string;
  summaryIsSynthetic?: boolean;
  runnerId: string;
  providerLabel?: string;
  storedModelId?: string;
}

function makeTaskFolder(
  name: string,
  extraProgress: Partial<TaskProgress> = {}
): { folderPath: string; folderUri: vscode.Uri; progress: TaskProgress } {
  const folderPath = path.join(REAL_ROOT, "plans", name);
  fs.mkdirSync(folderPath, { recursive: true });
  const progress: TaskProgress = {
    taskFolder: name,
    currentStage: "impl-high-review",
    status: "active",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    implReviewFiles: ["src/prior.ts"],
    ownership: {
      metaRoot: path.join(REAL_ROOT, "plans"),
      projectRoot: REAL_ROOT,
      workspaceRoot: REAL_ROOT,
      boundAt: "2026-01-01T00:00:00.000Z",
    },
    ...extraProgress,
  };
  fs.writeFileSync(
    path.join(folderPath, "task-progress.json"),
    JSON.stringify(progress, null, 2),
    "utf8"
  );
  fs.writeFileSync(path.join(folderPath, "task.md"), "# Task\n\nDo the thing.\n", "utf8");
  fs.writeFileSync(path.join(folderPath, "plan-final.md"), PLAN_FINAL, "utf8");
  fs.writeFileSync(path.join(folderPath, "impl-summary.md"), PRIOR_SUMMARY, "utf8");
  fs.writeFileSync(path.join(folderPath, "impl-summary_prev.md"), PRIOR_SUMMARY_PREV, "utf8");
  fs.writeFileSync(path.join(folderPath, "impl-high-review.md"), PRIOR_REVIEW, "utf8");
  return { folderPath, folderUri: vscode.Uri.file(folderPath), progress };
}

function makeButtonPressArg(folderPath: string, progress: TaskProgress): { task: IncompleteTask } {
  return {
    task: {
      folderUri: vscode.Uri.file(folderPath),
      folderName: path.basename(folderPath),
      progress,
      canonicalId: folderPath,
    },
  };
}

function installFsBridge(): { restore: () => void } {
  const target = vscode.workspace.fs as unknown as Record<string, unknown>;
  const orig = { ...target };
  target.readFile = (uri: vscode.Uri): Promise<Uint8Array> =>
    fs.promises.readFile(uri.fsPath).then((buf) => new Uint8Array(buf));
  target.writeFile = async (uri: vscode.Uri, content: Uint8Array): Promise<void> => {
    await fs.promises.mkdir(path.dirname(uri.fsPath), { recursive: true });
    await fs.promises.writeFile(uri.fsPath, content);
  };
  target.rename = async (
    source: vscode.Uri,
    dest: vscode.Uri,
    _options?: { overwrite?: boolean }
  ): Promise<void> => {
    await fs.promises.rm(dest.fsPath, { force: true });
    await fs.promises.rename(source.fsPath, dest.fsPath);
  };
  target.delete = (uri: vscode.Uri): Promise<void> =>
    fs.promises.rm(uri.fsPath, { force: true, recursive: true });
  target.createDirectory = (uri: vscode.Uri): Promise<void> =>
    fs.promises.mkdir(uri.fsPath, { recursive: true }).then(() => undefined);
  target.readDirectory = async (uri: vscode.Uri): Promise<[string, number][]> => {
    const entries = await fs.promises.readdir(uri.fsPath, { withFileTypes: true });
    return entries.map((entry) => [entry.name, entry.isDirectory() ? 2 : 1]);
  };
  target.stat = async (uri: vscode.Uri): Promise<{ type: number; size: number; ctime: number; mtime: number }> => {
    const stat = await fs.promises.stat(uri.fsPath);
    return {
      type: stat.isDirectory() ? 2 : 1,
      size: stat.size,
      ctime: stat.ctimeMs,
      mtime: stat.mtimeMs,
    };
  };
  return {
    restore: (): void => {
      for (const key of ["readFile", "writeFile", "rename", "delete", "createDirectory", "readDirectory", "stat"]) {
        target[key] = orig[key];
      }
    },
  };
}

function installWorkspaceFoldersStub(): { restore: () => void } {
  const ws = vscode.workspace as unknown as Record<string, unknown>;
  const orig = ws.workspaceFolders;
  ws.workspaceFolders = [{ uri: vscode.Uri.file(REAL_ROOT), name: "root", index: 0 }];
  return { restore: (): void => { ws.workspaceFolders = orig; } };
}

interface Patched { restore: () => void }

function patch(module: Record<string, unknown>, name: string, replacement: unknown): Patched {
  const orig = module[name];
  module[name] = replacement;
  return { restore: (): void => { module[name] = orig; } };
}

function makeExtensionContext(): vscode.ExtensionContext {
  const backing = new Map<string, unknown>([
    [
      `aiHelper.consent.v${DISCLAIMER_VERSION}`,
      { acceptedAt: "2026-01-01T00:00:00.000Z", version: DISCLAIMER_VERSION },
    ],
  ]);
  const memento = {
    keys: (): readonly string[] => [...backing.keys()],
    get: <T>(key: string, defaultValue?: T): T | undefined =>
      backing.has(key) ? (backing.get(key) as T) : defaultValue,
    update: (key: string, value: unknown): Thenable<void> => {
      if (value === undefined) { backing.delete(key); } else { backing.set(key, value); }
      return Promise.resolve();
    },
  };
  return {
    subscriptions: [] as vscode.Disposable[],
    extensionUri: vscode.Uri.file(REAL_ROOT),
    workspaceState: memento,
    globalState: memento,
  } as unknown as vscode.ExtensionContext;
}

interface HarnessRun {
  /** Every automation-chain dispatch recorded instead of executed. */
  dispatches: AutomationDispatch[];
  /** Prompts the fake provider boundary was invoked with. */
  prompts: string[];
  /**
   * Persisted pendingImplReviewFiles as read from DISK at the moment the run
   * log was written — the crash-order probe for "quarantine is durable first".
   */
  pendingAtRunLogWrite: string[][];
  /**
   * After every patchTaskProgressStrictV1 persist: the marker's presence and
   * whether the review artifact was stale-stamped at that instant, for the
   * marker-clear ordering invariant.
   */
  persistedStates: { markerSet: boolean; reviewStale: boolean }[];
  /**
   * Every status-surface notification the run emitted, with its action
   * command when one was attached — the reconciliation-affordance probe
   * (finding 3).
   */
  notifications: { message: string; actionCommand?: { command: string; title: string } }[];
}

async function runHarnessed(
  folderPath: string,
  progress: TaskProgress,
  result: FakeRunResult
): Promise<HarnessRun> {
  const provider = new StatusTreeProvider();
  initNotificationRouter(provider);
  const fsBridge = installFsBridge();
  const wsStub = installWorkspaceFoldersStub();
  const windowTarget = vscode.window as unknown as Record<string, unknown>;
  const origShowWarning = windowTarget.showWarningMessage;
  // The pre-run safety modal for a non-git workspace: always proceed.
  windowTarget.showWarningMessage = (): Promise<string> => Promise.resolve("Proceed Anyway");

  const run: HarnessRun = {
    dispatches: [],
    prompts: [],
    pendingAtRunLogWrite: [],
    persistedStates: [],
    notifications: [],
  };

  // Notification probe: NotificationRouter routes through the provider's
  // addEntry, whose sixth argument is the optional action command.
  const providerTarget = provider as unknown as {
    addEntry: (...args: unknown[]) => unknown;
  };
  const origAddEntry = providerTarget.addEntry.bind(provider);
  providerTarget.addEntry = (...args: unknown[]): unknown => {
    run.notifications.push({
      message: args[0] as string,
      actionCommand: args[5] as { command: string; title: string } | undefined,
    });
    return origAddEntry(...args);
  };

  const progressFile = path.join(folderPath, "task-progress.json");
  const reviewFile = path.join(folderPath, "impl-high-review.md");
  const origWriteRunLog = runLogModule.writeRunLog as (...args: unknown[]) => Promise<vscode.Uri>;
  const origPatch = progressWriterModule.patchTaskProgressStrictV1 as (
    ...args: unknown[]
  ) => Promise<TaskProgress | undefined>;

  const patches: Patched[] = [
    patch(automationChainModule, "scheduleAutomationChain", (dispatch: AutomationDispatch): Promise<boolean> => {
      run.dispatches.push(dispatch);
      return Promise.resolve(true);
    }),
    patch(runEditActionModule, "checkEditActionProviderPathGateV1", () => Promise.resolve({ ok: true })),
    patch(runEditActionModule, "checkEditActionAvailabilityV1", () => Promise.resolve({ ok: true })),
    patch(runEditActionModule, "runImplementationOrSealedV1", (options: { prompt: string }) => {
      run.prompts.push(options.prompt);
      return Promise.resolve(result);
    }),
    patch(modelSelectionModule, "resolveFreshModelForStage", () =>
      Promise.resolve({ modelId: "cli:test-model", source: "task" })),
    patch(runnerRegistryModule, "checkImplementationAvailabilityForModel", () =>
      Promise.resolve({ availability: { available: true }, providerLabel: "Test CLI" })),
    patch(contextPackModule, "generateContextPack", () => Promise.resolve("ctx")),
    patch(promptTemplatesModule, "renderPromptTemplate", () => Promise.resolve("BASE PROMPT")),
    patch(promptSizeGuardModule, "checkAndConfirmPromptSize", () => Promise.resolve("ok")),
    patch(settingsModule, "isAutoAdvanceEnabled", () => false),
    patch(settingsModule, "getAutoReviewAfterImplementationMode", () => "off"),
    // The harness root repo is all-untracked by design; the dirty-worktree
    // prompt is not what these tests exercise.
    patch(settingsModule, "allowsDirtyWorktreeChanges", () => true),
    patch(runLogModule, "writeRunLog", async (...args: unknown[]): Promise<vscode.Uri> => {
      // Crash-order probe: what is DURABLE at the instant the run log lands?
      const persisted = JSON.parse(fs.readFileSync(progressFile, "utf8")) as TaskProgress;
      run.pendingAtRunLogWrite.push([...(persisted.pendingImplReviewFiles ?? [])]);
      return origWriteRunLog(...args);
    }),
    patch(
      progressWriterModule,
      "patchTaskProgressStrictV1",
      async (...args: unknown[]): Promise<TaskProgress | undefined> => {
        const patched = await origPatch(...args);
        const persisted = JSON.parse(fs.readFileSync(progressFile, "utf8")) as TaskProgress;
        const review = fs.existsSync(reviewFile) ? fs.readFileSync(reviewFile, "utf8") : "";
        run.persistedStates.push({
          markerSet: persisted.reviewInvalidatedByRound !== undefined,
          reviewStale: review.trimStart().startsWith("# Review Stale"),
        });
        return patched;
      }
    ),
  ];

  const context = makeExtensionContext();
  try {
    await runImplementationWithAI(
      vscode.Uri.file(REAL_ROOT),
      context,
      makeButtonPressArg(folderPath, progress)
    );
  } finally {
    for (const p of patches.reverse()) { p.restore(); }
    windowTarget.showWarningMessage = origShowWarning;
    wsStub.restore();
    fsBridge.restore();
    provider.dispose();
    deactivateNotificationRouter();
  }
  return run;
}

/**
 * Read the persisted task-progress.json through the STRICT decoder (plain
 * node fs — the vscode fs bridge is already torn down when assertions run),
 * so every assertion also proves the state the run persisted is a document
 * the product's own fail-closed decoder accepts.
 */
function readProgress(folderPath: string): TaskProgress {
  const text = fs.readFileSync(path.join(folderPath, "task-progress.json"), "utf8");
  const decoded = decodeTaskProgressTextV1(text, {
    expectedTaskFolder: path.basename(folderPath),
  });
  assert.ok(decoded.ok, `persisted task-progress.json must strict-decode: ${decoded.ok ? "" : decoded.reason}`);
  return decoded.decoded.progress;
}

function readRunLogs(folderPath: string): string[] {
  const runsDir = path.join(folderPath, "runs");
  if (!fs.existsSync(runsDir)) {
    return [];
  }
  return fs
    .readdirSync(runsDir)
    .sort()
    .map((name) => fs.readFileSync(path.join(runsDir, name), "utf8"));
}

void describe("deferred/incomplete round recovery (end to end)", () => {
  void it("records a deferred round incomplete: artifacts preserved, delta quarantined durably before the run log, continuation scheduled", async () => {
    const { folderPath, progress } = makeTaskFolder("deferred_detect");
    const run = await runHarnessed(folderPath, progress, {
      status: "completed",
      filesChanged: ["src/newfile.ts"],
      filesChangedUnknown: false,
      summary: DEFERRED_RESPONSE,
      runnerId: "test-cli",
      providerLabel: "Test CLI",
      storedModelId: "cli:test-model",
    });

    // Artifacts byte-identical — no unusable-summary replacement, no stale
    // placeholder over the review's content.
    assert.equal(fs.readFileSync(path.join(folderPath, "impl-summary.md"), "utf8"), PRIOR_SUMMARY);
    assert.equal(
      fs.readFileSync(path.join(folderPath, "impl-summary_prev.md"), "utf8"),
      PRIOR_SUMMARY_PREV
    );
    assert.equal(
      fs.readFileSync(path.join(folderPath, "impl-high-review.md"), "utf8"),
      PRIOR_REVIEW
    );

    const persisted = readProgress(folderPath);
    assert.deepEqual(persisted?.pendingImplReviewFiles, ["src/newfile.ts"]);
    assert.deepEqual(
      persisted?.implReviewFiles,
      ["src/prior.ts"],
      "a detected round's delta must never be banked into implReviewFiles"
    );
    assert.equal(persisted?.incompleteRoundContinuations, 1);
    assert.equal(persisted?.reviewInvalidatedByRound?.stage, "impl-high-review");
    assert.equal(persisted?.status, "active");

    // Crash-order invariant: the quarantine was durable BEFORE the run log
    // was written — a crash after the log write can only lose reporting.
    assert.equal(run.pendingAtRunLogWrite.length, 1);
    assert.deepEqual(run.pendingAtRunLogWrite[0], ["src/newfile.ts"]);

    const logs = readRunLogs(folderPath);
    assert.equal(logs.length, 1);
    assert.match(logs[0]!, /Status: incomplete \(roundDeferred\)/);
    assert.match(logs[0]!, /## Incomplete round/);
    assert.match(logs[0]!, /- src\/newfile\.ts/);

    // Continuation scheduled; no review/auto-advance dispatch fired.
    assert.equal(run.dispatches.length, 1);
    assert.equal(run.dispatches[0]?.command, "vs-code-ai-helper.runImplementationWithAI");
    assert.equal(run.dispatches[0]?.chainId, "impl-continuation");
  });

  void it("treats an EMPTY completed response as the same incomplete round (no banking, no summary replacement)", async () => {
    const { folderPath, progress } = makeTaskFolder("deferred_empty");
    const run = await runHarnessed(folderPath, progress, {
      status: "completed",
      filesChanged: ["src/orphan.ts"],
      filesChangedUnknown: false,
      summary: "",
      runnerId: "test-cli",
      providerLabel: "Test CLI",
      storedModelId: "cli:test-model",
    });

    // The review blocker's exact failure: an empty response used to fall onto
    // the rejected-summary path, banking src/orphan.ts and replacing
    // impl-summary.md with the unusable placeholder.
    assert.equal(fs.readFileSync(path.join(folderPath, "impl-summary.md"), "utf8"), PRIOR_SUMMARY);
    const persisted = readProgress(folderPath);
    assert.deepEqual(persisted?.pendingImplReviewFiles, ["src/orphan.ts"]);
    assert.deepEqual(persisted?.implReviewFiles, ["src/prior.ts"]);

    const logs = readRunLogs(folderPath);
    assert.equal(logs.length, 1);
    assert.match(logs[0]!, /Status: incomplete \(roundIncomplete\)/);
    assert.equal(run.dispatches[0]?.chainId, "impl-continuation");
  });

  void it("a later successful round gets the Continuation Notice, promotes the pending set, and clears the marker only after replacement review state persists", async () => {
    const { folderPath, progress } = makeTaskFolder("deferred_promote", {
      pendingImplReviewFiles: ["src/newfile.ts"],
      incompleteRoundContinuations: 1,
      reviewInvalidatedByRound: { stage: "impl-high-review", at: "2026-01-02T00:00:00.000Z" },
    });
    const run = await runHarnessed(folderPath, progress, {
      status: "completed",
      filesChanged: ["src/resolver.ts"],
      filesChangedUnknown: false,
      summary: GOOD_SUMMARY,
      runnerId: "test-cli",
      providerLabel: "Test CLI",
      storedModelId: "cli:test-model",
    });

    // The continuation prompt names the unreported round's paths.
    assert.equal(run.prompts.length, 1);
    assert.match(run.prompts[0]!, /## Continuation Notice/);
    assert.match(run.prompts[0]!, /- src\/newfile\.ts/);

    const persisted = readProgress(folderPath);
    const banked = [...(persisted?.implReviewFiles ?? [])].sort();
    assert.deepEqual(
      banked,
      ["src/newfile.ts", "src/prior.ts", "src/resolver.ts"],
      "promotion unions the quarantined delta with the round's own delta"
    );
    assert.equal(persisted?.pendingImplReviewFiles, undefined);
    assert.equal(persisted?.incompleteRoundContinuations, undefined);
    assert.equal(persisted?.reviewInvalidatedByRound, undefined);

    // Replacement review-tracking state persisted: the stage's artifact is
    // now stale-stamped (its previous content is preserved as the _prev
    // backup by the stamp's own write path).
    const review = fs.readFileSync(path.join(folderPath, "impl-high-review.md"), "utf8");
    assert.ok(review.trimStart().startsWith("# Review Stale"));

    // Ordering invariant across EVERY persisted state, not just the final
    // one: at no point was the marker cleared while the review artifact still
    // read as current.
    for (const state of run.persistedStates) {
      assert.ok(
        state.markerSet || state.reviewStale,
        "a persisted state cleared the review-invalid marker before replacement review state was durable"
      );
    }
  });

  void it("escalates to human at the continuation cap — pausing the task despite an absent reviewAttemptId", async () => {
    const { folderPath, progress } = makeTaskFolder("deferred_cap", {
      incompleteRoundContinuations: MAX_INCOMPLETE_ROUND_CONTINUATIONS_V1 - 1,
      pendingImplReviewFiles: ["src/newfile.ts"],
      reviewInvalidatedByRound: { stage: "impl-high-review", at: "2026-01-02T00:00:00.000Z" },
    });
    const run = await runHarnessed(folderPath, progress, {
      status: "completed",
      filesChanged: ["src/more.ts"],
      filesChangedUnknown: false,
      summary: DEFERRED_RESPONSE,
      runnerId: "test-cli",
      providerLabel: "Test CLI",
      storedModelId: "cli:test-model",
    });

    const persisted = readProgress(folderPath);
    assert.equal(persisted?.incompleteRoundContinuations, MAX_INCOMPLETE_ROUND_CONTINUATIONS_V1);
    assert.equal(
      persisted?.status,
      "paused",
      "cap exhaustion must pause the task even with no reviewAttemptId on an implementation-stage task"
    );
    assert.equal(persisted?.escalation?.kind, "plateau");
    // Both incomplete rounds' deltas stay quarantined, nothing banked.
    assert.deepEqual(
      [...(persisted?.pendingImplReviewFiles ?? [])].sort(),
      ["src/more.ts", "src/newfile.ts"]
    );
    assert.deepEqual(persisted?.implReviewFiles, ["src/prior.ts"]);

    // No continuation scheduled once the cap is exhausted.
    assert.equal(
      run.dispatches.some((d) => d.chainId === "impl-continuation"),
      false
    );
  });
});

/**
 * Part 2 (finding 2): `implReviewFiles` comes from the round's own report.
 *
 * The pinned leak mechanism (round 015 of "more workflow bugs", 2026-08-13):
 * the before/after git snapshot diff spans the round's wall-clock window, not
 * its authorship, so files edited BY HAND in the same workspace while the
 * round ran (the user's own Claude Code session — sessionManagerV1.ts,
 * appServicesV1.ts, …) landed in the diff and were banked verbatim: the round
 * self-reported 2 changed files, the workflow banked 8. Banking now
 * intersects the snapshot with the round's `## Files Changed` self-report.
 */
void describe("round file attribution (end to end)", () => {
  void it("pause-window files untouched by the round never enter implReviewFiles, and are logged as unattributed", async () => {
    const { folderPath, progress } = makeTaskFolder("attribution_leak");
    await runHarnessed(folderPath, progress, {
      status: "completed",
      // The snapshot saw both; the summary (GOOD_SUMMARY) reports only
      // src/resolver.ts — apps/mobile/hand-edit.ts is the concurrent hand edit.
      filesChanged: ["apps/mobile/hand-edit.ts", "src/resolver.ts"],
      filesChangedUnknown: false,
      summary: GOOD_SUMMARY,
      runnerId: "test-cli",
      providerLabel: "Test CLI",
      storedModelId: "cli:test-model",
    });

    const persisted = readProgress(folderPath);
    assert.deepEqual(
      [...(persisted?.implReviewFiles ?? [])].sort(),
      ["src/prior.ts", "src/resolver.ts"],
      "only the round's self-reported delta may be banked as review scope"
    );
    assert.equal(persisted?.pendingImplReviewFiles, undefined);

    // Visible, not silent: the run file names the excluded remainder.
    const logs = readRunLogs(folderPath);
    assert.equal(logs.length, 1);
    assert.match(logs[0]!, /## Unattributed workspace changes/);
    assert.match(logs[0]!, /- apps\/mobile\/hand-edit\.ts/);
    assert.doesNotMatch(logs[0]!, /## Unattributed workspace changes[\s\S]*src\/resolver\.ts/);
  });

  void it("a file edited by hand during a pause AND modified by the round stays in scope via the intersection", async () => {
    const { folderPath, progress } = makeTaskFolder("attribution_both");
    const bothEditedSummary = GOOD_SUMMARY.replace(
      "- `src/resolver.ts` — added the resolver",
      "- `src/resolver.ts` — added the resolver\n- `src/both-edited.ts` — reworked during the round"
    );
    await runHarnessed(folderPath, progress, {
      status: "completed",
      filesChanged: ["src/both-edited.ts", "src/resolver.ts"],
      filesChangedUnknown: false,
      summary: bothEditedSummary,
      runnerId: "test-cli",
      providerLabel: "Test CLI",
      storedModelId: "cli:test-model",
    });

    const persisted = readProgress(folderPath);
    assert.deepEqual(
      [...(persisted?.implReviewFiles ?? [])].sort(),
      ["src/both-edited.ts", "src/prior.ts", "src/resolver.ts"]
    );
    const logs = readRunLogs(folderPath);
    assert.doesNotMatch(logs[0]!, /## Unattributed workspace changes/);
  });

  void it("pending-set promotion unions files changed only by a deferred round, while unattributed files stay excluded", async () => {
    const { folderPath, progress } = makeTaskFolder("attribution_promote", {
      pendingImplReviewFiles: ["src/deferred-only.ts"],
      incompleteRoundContinuations: 1,
      reviewInvalidatedByRound: { stage: "impl-high-review", at: "2026-01-02T00:00:00.000Z" },
    });
    await runHarnessed(folderPath, progress, {
      status: "completed",
      filesChanged: ["apps/mobile/hand-edit.ts", "src/resolver.ts"],
      filesChangedUnknown: false,
      summary: GOOD_SUMMARY,
      runnerId: "test-cli",
      providerLabel: "Test CLI",
      storedModelId: "cli:test-model",
    });

    const persisted = readProgress(folderPath);
    assert.deepEqual(
      [...(persisted?.implReviewFiles ?? [])].sort(),
      ["src/deferred-only.ts", "src/prior.ts", "src/resolver.ts"],
      "promotion must union the deferred round's files; the hand edit must still be excluded"
    );
    assert.equal(persisted?.pendingImplReviewFiles, undefined);
  });

  void it("filesChangedUnknown never banks anything — an unenumerable change set is not a dirty scan license", async () => {
    const { folderPath, progress } = makeTaskFolder("attribution_unknown");
    await runHarnessed(folderPath, progress, {
      status: "completed",
      filesChanged: [],
      filesChangedUnknown: true,
      summary: GOOD_SUMMARY,
      runnerId: "test-cli",
      providerLabel: "Test CLI",
      storedModelId: "cli:test-model",
    });

    const persisted = readProgress(folderPath);
    assert.deepEqual(persisted?.implReviewFiles, ["src/prior.ts"]);
    const logs = readRunLogs(folderPath);
    assert.doesNotMatch(logs[0]!, /## Unattributed workspace changes/);
  });
});

/**
 * Part 4 (finding 3): while `checklistProgressUnreliable` is set the loop
 * keeps running, but never silently — the round's own file records that the
 * counts are unverified, a notification carries the one affordance that can
 * clear the latch (reconcilePlanChecklist), and no round clears it
 * automatically. The count-gating stand-down and the "N of M" qualifier are
 * covered in reconcilePlanChecklistCommand.test.ts.
 */
void describe("checklist reconciliation prompt while the latch is set", () => {
  void it("a completed round under the latch appends the run-log note, surfaces the reconcile affordance, and leaves the latch set", async () => {
    const { folderPath, progress } = makeTaskFolder("latched_prompt", {
      checklistProgressUnreliable: true,
    });
    const run = await runHarnessed(folderPath, progress, {
      status: "completed",
      filesChanged: ["src/resolver.ts"],
      filesChangedUnknown: false,
      summary: GOOD_SUMMARY,
      runnerId: "test-cli",
      providerLabel: "Test CLI",
      storedModelId: "cli:test-model",
    });

    // No automatic reconciliation: a successful round must NOT clear the
    // latch — only the explicit human confirmation may.
    const persisted = readProgress(folderPath);
    assert.equal(persisted?.checklistProgressUnreliable, true);

    const logs = readRunLogs(folderPath);
    assert.equal(logs.length, 1);
    assert.match(logs[0]!, /## Checklist reconciliation needed/);
    assert.match(logs[0]!, /Mark Plan Checklist Reconciled/);

    const affordance = run.notifications.find(
      (n) => n.actionCommand?.command === "vs-code-ai-helper.reconcilePlanChecklist"
    );
    assert.ok(affordance, "a notification must carry the reconcile affordance");
    assert.match(affordance.message, /unverified/);
  });

  void it("an unlatched round surfaces no reconciliation prompt", async () => {
    const { folderPath, progress } = makeTaskFolder("unlatched_no_prompt");
    const run = await runHarnessed(folderPath, progress, {
      status: "completed",
      filesChanged: ["src/resolver.ts"],
      filesChangedUnknown: false,
      summary: GOOD_SUMMARY,
      runnerId: "test-cli",
      providerLabel: "Test CLI",
      storedModelId: "cli:test-model",
    });

    const logs = readRunLogs(folderPath);
    assert.doesNotMatch(logs[0]!, /## Checklist reconciliation needed/);
    assert.equal(
      run.notifications.some(
        (n) => n.actionCommand?.command === "vs-code-ai-helper.reconcilePlanChecklist"
      ),
      false
    );
  });
});
