/**
 * Coverage for the `generateImplementation.v1` registry row's promotion path
 * — specifically the durable provider/model attribution task's deliberate
 * design decision for `plan-final.md`-style artifacts: the attribution
 * header is prepended ABOVE the pre-existing `IMPLEMENTATION_CHECKLIST_MARKER`
 * prepend, so both `.includes()` marker consumers (this row's own idempotent
 * prepend check, and `reviewActions.ts`'s `executeImplementationRun` read)
 * keep finding the marker regardless of a header occupying the top of the
 * file.
 */
import * as assert from "node:assert/strict";
import * as fs from "node:fs";
import * as path from "node:path";
import { after, before, describe, it } from "node:test";

import { createGenerateImplementationRowV1 } from "../actions/rows/generateImplementationRowV1";
import { TaskActionExecutionContextV1 } from "../actions/taskActionRegistryV1";
import {
  ensureWorkflowTaskFolderRootV1,
  resetWorkflowRuntimeServicesForTestV1,
} from "../services/workflowRuntimeServicesV1";
import { allocateHex128IdV1 } from "../types/actionCorrelationV1";
import { makeOwnedTaskFolder } from "./taskFolderFixture";

const IMPLEMENTATION_CHECKLIST_MARKER = "<!-- ensemble:implementation-checklist -->";

function fakeContext(overrides: {
  validatedInput: unknown;
  provider?: { providerLabel: string; storedModelId: string };
}): TaskActionExecutionContextV1 {
  return {
    correlation: {
      actionKey: "generateImplementation.v1",
      operationId: allocateHex128IdV1(),
      attemptId: allocateHex128IdV1(),
      taskBindingId: allocateHex128IdV1(),
      chatDocumentId: allocateHex128IdV1(),
    },
    stage: "impl",
    validatedInput: overrides.validatedInput,
    ...(overrides.provider ? { provider: overrides.provider } : {}),
  };
}

void describe("generateImplementationRowV1 — attribution header / checklist marker ordering", () => {
  let taskFolder: string;

  before(() => {
    resetWorkflowRuntimeServicesForTestV1();
    taskFolder = makeOwnedTaskFolder("ensemble-generate-impl-attribution-").folder;
  });
  after(() => {
    resetWorkflowRuntimeServicesForTestV1();
    fs.rmSync(taskFolder, { recursive: true, force: true });
  });

  void it("stamps the attribution header ABOVE the checklist marker, and the marker stays independently detectable via .includes()", async () => {
    const rootId = ensureWorkflowTaskFolderRootV1(taskFolder);
    const relativePath = "implementation-1.md";
    const row = createGenerateImplementationRowV1();
    const context = fakeContext({
      validatedInput: { prompt: "do it", targetLocator: { rootId, relativePath } },
      provider: { providerLabel: "Test Provider", storedModelId: "copilot:test" },
    });
    const outcome = await row.promoteCompletedContent(
      { contentType: "markdown-artifact.v1", schemaVersion: 1, markdown: "# Implementation Notes\n\nDone.\n" },
      context
    );
    assert.equal(outcome, "completed");

    const written = fs.readFileSync(path.join(taskFolder, relativePath), "utf8");
    assert.ok(
      written.startsWith("<!-- Generated by Test Provider (test) -->"),
      "attribution header must be first, matching review-artifact header format"
    );
    assert.ok(
      written.includes(IMPLEMENTATION_CHECKLIST_MARKER),
      "checklist marker must still be present for the row's own .includes() re-check"
    );
    const headerIndex = written.indexOf("<!-- Generated by");
    const markerIndex = written.indexOf(IMPLEMENTATION_CHECKLIST_MARKER);
    assert.ok(
      headerIndex >= 0 && markerIndex > headerIndex,
      "the deliberate ordering is header first, then the checklist marker"
    );

    // Simulate reviewActions.ts's own consumer, which reads the artifact raw
    // and scans it with a plain .includes() — never header-aware — proving
    // the marker is found regardless of a header occupying the top of the
    // file (AC 7 / plan step-14 item (f)).
    assert.equal(written.includes(IMPLEMENTATION_CHECKLIST_MARKER), true);
  });

  void it("omits the attribution header when the coordinator supplied no claimed reservation identity", async () => {
    const rootId = ensureWorkflowTaskFolderRootV1(taskFolder);
    const relativePath = "implementation-2.md";
    const row = createGenerateImplementationRowV1();
    const context = fakeContext({
      validatedInput: { prompt: "do it", targetLocator: { rootId, relativePath } },
    });
    const outcome = await row.promoteCompletedContent(
      { contentType: "markdown-artifact.v1", schemaVersion: 1, markdown: "# Implementation Notes\n\nDone.\n" },
      context
    );
    assert.equal(outcome, "completed");
    const written = fs.readFileSync(path.join(taskFolder, relativePath), "utf8");
    assert.ok(!written.includes("<!-- Generated by"), "no provider identity means no attribution header");
    assert.ok(written.startsWith(IMPLEMENTATION_CHECKLIST_MARKER), "the marker still prepends when no header is added");
  });

  void it("does not escape or otherwise transform quoted markdown — proves the write path is not the source of the field-report tick corruption", async () => {
    // 2026-08-12 field report item 1: a task's plan-final.md was found on
    // disk with every double quote backslash-escaped, breaking checklist
    // merge matching for rounds afterward. This regression pins that
    // `promoteGenerateImplementationContentV1` writes `content.markdown`
    // byte-for-byte (module comment traces why the corruption, if it
    // recurs, cannot originate here or in envelope parsing).
    const rootId = ensureWorkflowTaskFolderRootV1(taskFolder);
    const relativePath = "implementation-quotes.md";
    const row = createGenerateImplementationRowV1();
    const context = fakeContext({
      validatedInput: { prompt: "do it", targetLocator: { rootId, relativePath } },
    });
    const quotedMarkdown =
      '- [ ] Surface a friendly "database waking up" state on first-connect errors.\n' +
      "- [ ] Handle the driver's PKCE `state` field.\n";
    const outcome = await row.promoteCompletedContent(
      { contentType: "markdown-artifact.v1", schemaVersion: 1, markdown: quotedMarkdown },
      context
    );
    assert.equal(outcome, "completed");
    const written = fs.readFileSync(path.join(taskFolder, relativePath), "utf8");
    assert.ok(
      written.includes('Surface a friendly "database waking up" state'),
      "quotes must survive unescaped, exactly as supplied in content.markdown"
    );
    assert.ok(!written.includes('\\"'), "the write path must never introduce backslash-escaped quotes");
  });
});
