/**
 * Coverage for review-artifact freshness (the 2026-08-14 follow-up): a review
 * whose recorded `reviewed-commit` is no longer HEAD must SAY so at the top
 * of the artifact, not only in a trailing HTML comment.
 *
 *  - reviewReadiness.ts's computeReviewFreshness / upsertStaleReviewBanner /
 *    withVisibleReviewedCommitLineV1 (pure transforms);
 *  - reviewFreshness.ts's refreshStaleReviewBannerForArtifactV1, the IO
 *    helper the View Review path runs before opening an artifact — exercised
 *    here against an artifact shaped exactly like the observed failure
 *    (.ensemble/2026-08-13_task_1/impl-high-review.md: trailing comment only,
 *    commit behind HEAD, no freshness marker anywhere).
 */
import * as assert from "node:assert/strict";
import * as nodeFs from "node:fs";
import * as nodeOs from "node:os";
import * as nodePath from "node:path";
import { after, describe, it } from "node:test";
import * as vscode from "vscode";

import {
  computeReviewFreshness,
  isStrictPerfectReview,
  parseReadiness,
  parseReviewBlockersDetailed,
  parseReviewedCommitSha,
  parseReviewProgress,
  upsertStaleReviewBanner,
  withVisibleReviewedCommitLineV1,
} from "../utils/reviewReadiness";
import { refreshStaleReviewBannerForArtifactV1 } from "../utils/reviewFreshness";
import { safeRemoveDir } from "./testFsUtils";

const HEAD = "aaaaaaa1111111222222333333444444555555";
const REVIEWED = "7d24af24afffc4e976096e5ecd805962a7e2d28a";

/** The observed-failure shape: trailing HTML comment only, no visible marker. */
function jesterShapedReview(): string {
  return [
    "<!-- Generated by OpenAI Codex (gpt-5.6-sol@high) -->",
    "",
    "Readiness: 10/10",
    "",
    "## Summary verdict",
    "",
    "On track — all 15 ordered steps are complete and verified.",
    "",
    "<!-- blockers:start -->",
    "<!-- blockers:end -->",
    "",
    `<!-- reviewed-commit: ${REVIEWED} -->`,
    "",
    "<!-- progress: 15/15 -->",
    "",
  ].join("\n");
}

const EXPECTED_BANNER = `> ⚠ Stale: this review examined ${REVIEWED}, which is no longer HEAD.`;


void describe("computeReviewFreshness", () => {
  void it("reports behind-HEAD only when both SHAs are known and differ", () => {
    assert.deepEqual(computeReviewFreshness(jesterShapedReview(), HEAD), {
      reviewedSha: REVIEWED,
      behindHead: true,
    });
    assert.deepEqual(computeReviewFreshness(jesterShapedReview(), REVIEWED), {
      reviewedSha: REVIEWED,
      behindHead: false,
    });
    // The 7-char short form of the same commit is the same commit.
    assert.deepEqual(computeReviewFreshness(jesterShapedReview(), REVIEWED.slice(0, 7)), {
      reviewedSha: REVIEWED,
      behindHead: false,
    });
  });

  void it("never reports stale when freshness cannot be determined", () => {
    // No marker in the content.
    assert.deepEqual(computeReviewFreshness("Readiness: 8/10\n", HEAD), {
      reviewedSha: undefined,
      behindHead: false,
    });
    // No HEAD to compare against.
    assert.deepEqual(computeReviewFreshness(jesterShapedReview(), undefined), {
      reviewedSha: REVIEWED,
      behindHead: false,
    });
  });
});

void describe("upsertStaleReviewBanner", () => {
  void it("inserts the banner immediately after the leading Readiness line", () => {
    const out = upsertStaleReviewBanner(jesterShapedReview(), HEAD);
    const lines = out.split("\n");
    const readinessIndex = lines.indexOf("Readiness: 10/10");
    assert.ok(readinessIndex >= 0);
    assert.strictEqual(lines[readinessIndex + 1], EXPECTED_BANNER);
    // Nothing else moved: dropping the banner line reproduces the input.
    lines.splice(readinessIndex + 1, 1);
    assert.strictEqual(lines.join("\n"), jesterShapedReview());
  });

  void it("is idempotent — upserting twice equals upserting once", () => {
    const once = upsertStaleReviewBanner(jesterShapedReview(), HEAD);
    assert.strictEqual(upsertStaleReviewBanner(once, HEAD), once);
  });

  void it("refreshes a leftover banner when the recorded SHA differs", () => {
    const stale = upsertStaleReviewBanner(jesterShapedReview(), HEAD);
    const refreshed = upsertStaleReviewBanner(
      stale.replace(`<!-- reviewed-commit: ${REVIEWED} -->`, "<!-- reviewed-commit: bbbbbbb -->"),
      HEAD
    );
    assert.ok(refreshed.includes("> ⚠ Stale: this review examined bbbbbbb, which is no longer HEAD."));
    assert.ok(!refreshed.includes(REVIEWED + ", which is no longer HEAD"));
  });

  void it("is a no-op when the recorded commit matches HEAD, and removes a leftover banner", () => {
    assert.strictEqual(upsertStaleReviewBanner(jesterShapedReview(), REVIEWED), jesterShapedReview());
    const stale = upsertStaleReviewBanner(jesterShapedReview(), HEAD);
    // HEAD moving back onto the reviewed commit (or a mistaken banner) heals.
    assert.strictEqual(upsertStaleReviewBanner(stale, REVIEWED), jesterShapedReview());
  });

  void it("is a no-op for # Review Stale placeholders, marker-less content, and unknown HEAD", () => {
    const placeholder = "# Review Stale\n\nThis review was generated before plan.md was updated.\n";
    assert.strictEqual(upsertStaleReviewBanner(placeholder, HEAD), placeholder);
    const noMarker = "Readiness: 8/10\n\nNo commit marker here.\n";
    assert.strictEqual(upsertStaleReviewBanner(noMarker, HEAD), noMarker);
    assert.strictEqual(upsertStaleReviewBanner(jesterShapedReview(), undefined), jesterShapedReview());
  });
});

void describe("withVisibleReviewedCommitLineV1 (write time)", () => {
  void it("inserts the visible line after the Readiness line, keeping the HTML comment", () => {
    const out = withVisibleReviewedCommitLineV1(jesterShapedReview());
    const lines = out.split("\n");
    const readinessIndex = lines.indexOf("Readiness: 10/10");
    assert.ok(readinessIndex >= 0);
    assert.strictEqual(lines[readinessIndex + 1], `> Reviewed commit: ${REVIEWED}`);
    assert.ok(out.includes(`<!-- reviewed-commit: ${REVIEWED} -->`));
  });

  void it("is idempotent and strips any echoed stale banner from a fresh review", () => {
    const once = withVisibleReviewedCommitLineV1(jesterShapedReview());
    assert.strictEqual(withVisibleReviewedCommitLineV1(once), once);
    // A model that echoes the previous review's banner into its own fresh
    // review has it stripped: a review being written now is not stale.
    const withBanner = upsertStaleReviewBanner(jesterShapedReview(), HEAD);
    const cleaned = withVisibleReviewedCommitLineV1(withBanner);
    assert.ok(!cleaned.includes("⚠ Stale"));
    assert.ok(cleaned.includes(`> Reviewed commit: ${REVIEWED}`));
  });

  void it("returns marker-less content unchanged", () => {
    const plain = "Readiness: 8/10\n\nNo marker.\n";
    assert.strictEqual(withVisibleReviewedCommitLineV1(plain), plain);
  });
});

void describe("freshness markers do not disturb existing parsers", () => {
  const marked = withVisibleReviewedCommitLineV1(upsertStaleReviewBanner(jesterShapedReview(), HEAD));

  void it("Readiness score parsing is unaffected", () => {
    assert.deepEqual(parseReadiness(marked), { score: 10, label: "10/10" });
    assert.ok(isStrictPerfectReview(marked), "a bannered 10/10 review must still read as strict-perfect");
  });

  void it("the blockers block, progress marker, and reviewed-commit parsing are unaffected", () => {
    const blockers = parseReviewBlockersDetailed(marked);
    assert.ok(blockers.blockPresent);
    assert.deepEqual(blockers.blockers, []);
    assert.deepEqual(parseReviewProgress(marked), { complete: 15, total: 15 });
    // The visible line is not the comment form — the marker parse is unchanged.
    assert.strictEqual(parseReviewedCommitSha(marked), REVIEWED);
  });
});

void describe("refreshStaleReviewBannerForArtifactV1 (the View Review path's IO half)", () => {
  const ROOT = nodeFs.mkdtempSync(nodePath.join(nodeOs.tmpdir(), "ensemble-review-freshness-"));
  after(() => {
    safeRemoveDir(ROOT);
  });

  /** Back the stub's notImplemented workspace.fs read/write with the real fs. */
  function installFsStub(): () => void {
    const fsRecord = vscode.workspace.fs as unknown as Record<string, unknown>;
    const originalRead = fsRecord.readFile;
    const originalWrite = fsRecord.writeFile;
    fsRecord.readFile = (uri: vscode.Uri): Promise<Uint8Array> =>
      nodeFs.promises.readFile(uri.fsPath) as Promise<Uint8Array>;
    fsRecord.writeFile = (uri: vscode.Uri, content: Uint8Array): Promise<void> =>
      nodeFs.promises.writeFile(uri.fsPath, content).then(() => undefined);
    return (): void => {
      fsRecord.readFile = originalRead;
      fsRecord.writeFile = originalWrite;
    };
  }

  void it("a behind-HEAD artifact shaped like the observed failure gains the banner under its Readiness line in one pass", async () => {
    // Exactly the 2026-08-13_task_1 impl-high-review.md shape: attribution
    // header, confident verdict, trailing reviewed-commit comment — and no
    // freshness marker anywhere.
    const file = nodePath.join(ROOT, "impl-high-review.md");
    nodeFs.writeFileSync(file, jesterShapedReview(), "utf8");
    const uri = vscode.Uri.file(file);
    const restore = installFsStub();
    try {
      const written = await refreshStaleReviewBannerForArtifactV1(uri, HEAD);
      assert.ok(written, "a behind-HEAD review must be rewritten with the banner");
      const onDisk = nodeFs.readFileSync(file, "utf8");
      const lines = onDisk.split("\n");
      const readinessIndex = lines.indexOf("Readiness: 10/10");
      assert.ok(readinessIndex >= 0);
      assert.strictEqual(lines[readinessIndex + 1], EXPECTED_BANNER);
      assert.ok(onDisk.includes(`<!-- reviewed-commit: ${REVIEWED} -->`));

      // Second pass is a no-op: idempotent at the IO layer too.
      const again = await refreshStaleReviewBannerForArtifactV1(uri, HEAD);
      assert.strictEqual(again, false);
      assert.strictEqual(nodeFs.readFileSync(file, "utf8"), onDisk);

      // HEAD moving back onto the reviewed commit heals the artifact.
      const healed = await refreshStaleReviewBannerForArtifactV1(uri, REVIEWED);
      assert.ok(healed);
      assert.strictEqual(nodeFs.readFileSync(file, "utf8"), jesterShapedReview());
    } finally {
      restore();
    }
  });

  void it("leaves a # Review Stale placeholder and a current review untouched", async () => {
    const placeholderFile = nodePath.join(ROOT, "impl-low-review.md");
    nodeFs.writeFileSync(
      placeholderFile,
      "# Review Stale\n\nThis review was generated before workspace files were updated.\n",
      "utf8"
    );
    const currentFile = nodePath.join(ROOT, "publish-review.md");
    nodeFs.writeFileSync(currentFile, jesterShapedReview(), "utf8");
    const restore = installFsStub();
    try {
      assert.strictEqual(
        await refreshStaleReviewBannerForArtifactV1(vscode.Uri.file(placeholderFile), HEAD),
        false
      );
      assert.strictEqual(
        await refreshStaleReviewBannerForArtifactV1(vscode.Uri.file(currentFile), REVIEWED),
        false
      );
      // Unresolvable HEAD never marks anything.
      assert.strictEqual(
        await refreshStaleReviewBannerForArtifactV1(vscode.Uri.file(currentFile), undefined),
        false
      );
    } finally {
      restore();
    }
  });
});


