import * as vscode from "vscode";
import { PLAN_FILENAME } from "../types/taskProgress";

/**
 * Build a signed attribution line for AI-generated output, so the file
 * records which agent/model actually produced it rather than leaving that
 * to whatever (if anything) the agent itself self-reports in its answer —
 * e.g. an inherited/leaked session identity from the calling process.
 */
export function attributionHeader(
  providerLabel: string,
  modelLabel: string | undefined
): string {
  const model = modelLabel ? ` (${modelLabel})` : "";
  return `<!-- Generated by ${providerLabel}${model} -->`;
}

/**
 * Prepend an attribution header to generated content before it's written to
 * an output file, separated by a blank line.
 */
export function withAttribution(
  content: string,
  providerLabel: string,
  modelLabel: string | undefined
): string {
  return `${attributionHeader(providerLabel, modelLabel)}\n\n${content}`;
}

function findOpenDocument(fileUri: vscode.Uri): vscode.TextDocument | undefined {
  return vscode.workspace.textDocuments.find(
    (doc) => doc.uri.toString() === fileUri.toString()
  );
}

/**
 * Read a text file's content, preferring an open editor buffer so unsaved
 * changes are included.
 */
export async function readTextIfExists(
  fileUri: vscode.Uri
): Promise<string | undefined> {
  const openDoc = findOpenDocument(fileUri);
  if (openDoc) {
    return openDoc.getText();
  }

  try {
    const content = await vscode.workspace.fs.readFile(fileUri);
    return new TextDecoder().decode(content);
  } catch {
    return undefined;
  }
}

/**
 * Read a text file's trimmed content, or undefined if it doesn't exist or
 * is empty/whitespace-only.
 */
export async function readNonEmptyText(
  fileUri: vscode.Uri
): Promise<string | undefined> {
  const content = await readTextIfExists(fileUri);
  const trimmed = content?.trim();
  return trimmed && trimmed.length > 0 ? trimmed : undefined;
}

/**
 * Stat a file, or undefined if it doesn't exist.
 */
export async function statIfExists(
  fileUri: vscode.Uri
): Promise<vscode.FileStat | undefined> {
  try {
    return await vscode.workspace.fs.stat(fileUri);
  } catch {
    return undefined;
  }
}

/**
 * Write a text file, replacing the contents of an open editor buffer when
 * present so the visible document and on-disk file stay in sync.
 */
export async function writeTextFile(
  fileUri: vscode.Uri,
  content: string
): Promise<void> {
  const openDoc = findOpenDocument(fileUri);
  if (!openDoc) {
    await vscode.workspace.fs.writeFile(
      fileUri,
      new TextEncoder().encode(content)
    );
    return;
  }

  const fullRange = new vscode.Range(
    openDoc.positionAt(0),
    openDoc.positionAt(openDoc.getText().length)
  );
  const edit = new vscode.WorkspaceEdit();
  edit.replace(fileUri, fullRange, content);

  const applied = await vscode.workspace.applyEdit(edit);
  if (!applied) {
    throw new Error(`Failed to update ${fileUri.fsPath}.`);
  }

  const updatedDoc = findOpenDocument(fileUri) ?? openDoc;
  const saved = await updatedDoc.save();
  if (!saved) {
    throw new Error(`Failed to save ${fileUri.fsPath}.`);
  }
}

/**
 * Find open editor tabs for a file, or for anything under a directory path
 * (so a recursive directory delete also matches its open descendants).
 */
function findOpenTabsUnder(fileUri: vscode.Uri): vscode.Tab[] {
  const target = fileUri.toString();
  const targetPrefix = target.endsWith("/") ? target : target + "/";
  return vscode.window.tabGroups.all
    .flatMap((group) => group.tabs)
    .filter((tab) => {
      if (!(tab.input instanceof vscode.TabInputText)) {
        return false;
      }
      const tabUriString = tab.input.uri.toString();
      return tabUriString === target || tabUriString.startsWith(targetPrefix);
    });
}

/**
 * Delete a file or directory (recursively), first closing any open editor
 * tabs for it (or, for a directory, its descendants) so a stale dirty
 * buffer can't resurrect the deleted path on save.
 *
 * Throws without deleting anything if a tab couldn't be closed (e.g. the
 * user cancelled a save-changes prompt for a dirty buffer).
 */
export async function deletePath(fileUri: vscode.Uri): Promise<void> {
  const tabs = findOpenTabsUnder(fileUri);
  if (tabs.length > 0) {
    const closed = await vscode.window.tabGroups.close(tabs, false);
    if (!closed) {
      throw new Error(
        `Could not close open editor(s) for ${fileUri.fsPath}; deletion aborted.`
      );
    }
  }
  await vscode.workspace.fs.delete(fileUri, {
    recursive: true,
    useTrash: false,
  });
}

/**
 * Open a document in the editor, creating it empty first if it doesn't
 * exist.
 */
export async function openOrCreateDocument(
  fileUri: vscode.Uri,
  initialContent = ""
): Promise<void> {
  const existing = await statIfExists(fileUri);
  if (!existing) {
    await vscode.workspace.fs.writeFile(
      fileUri,
      new TextEncoder().encode(initialContent)
    );
  }
  const doc = await vscode.workspace.openTextDocument(fileUri);
  await vscode.window.showTextDocument(doc);
}

/**
 * Resolve the URI holding the task's CURRENT plan text.
 *
 * The current pipeline keeps a single plan.md that is revised in place, but
 * tasks created before 0.6.0 may have their latest revision in
 * plan-updated.md. That file wins only while it is newer than plan.md —
 * the first in-place update to plan.md takes over from then on.
 */
export async function resolveCurrentPlanUri(
  taskFolderUri: vscode.Uri
): Promise<vscode.Uri> {
  const planUri = vscode.Uri.joinPath(taskFolderUri, PLAN_FILENAME);
  const legacyUpdatedUri = vscode.Uri.joinPath(
    taskFolderUri,
    "plan-updated.md"
  );

  const [planStat, legacyStat, legacyContent] = await Promise.all([
    statIfExists(planUri),
    statIfExists(legacyUpdatedUri),
    readNonEmptyText(legacyUpdatedUri),
  ]);

  if (
    legacyStat &&
    legacyContent &&
    (!planStat || legacyStat.mtime > planStat.mtime)
  ) {
    return legacyUpdatedUri;
  }
  return planUri;
}
