import * as vscode from "vscode";
import { AgentRunRequest, AgentRunResult } from "../types/agentRunner";
import type { TaskStage } from "../types/taskProgress";
import { notifyDesktop } from "./desktopNotifier";
import { taskOperations } from "./taskOperations";
import { NotificationRouter } from "./notificationRouter";

export interface PendingResumeOperation {
  request: Omit<AgentRunRequest, "taskFolderUri" | "workspaceUri" | "outputFile"> & {
    taskFolderPath: string; workspacePath: string; outputFilePath: string;
  };
  attempts: number;
  createdAt: string;
}

const KEY = "pendingQuotaResume";
// Deliberately excludes a bare "exceeded" marker: real quota phrasing
// already matches via "quota"/"rate limit"/"usage limit"/"session limit" (e.g. "exceeded
// your current quota" matches on "quota" alone), while "exceeded" alone
// would false-positive on unrelated errors like "context length exceeded"
// or an argv-size cap message.
const QUOTA_MARKERS = ["quota", "rate limit", "ratelimit", "credits", "credit limit", "usage limit", "session limit"];
const TEMPORARY_MARKERS = ["temporarily unavailable", "service unavailable", "too many requests", "try again later"];
// Transport-level failures: the request/stream died in transit rather than the
// service answering with a refusal. Kept separate from TEMPORARY_MARKERS so the
// two intents stay auditable — TEMPORARY_MARKERS means "the server said no for
// now", these mean "nobody said anything, the pipe broke".
//
// Deliberately narrow. Anything vaguer ("network error", "connection closed",
// "stream error") is a phrase that occurs in ordinary source code, and for
// providers whose failure detail is still raw stdout (kiro-cli, codex-cli both
// echo file contents / model prose into it) a loose marker would classify an
// unrelated failure as retryable and burn a backup allocation.
//
// "streaming response failed" is opencode's wording, taken verbatim from a
// captured production failure: an event-stream line
// {"type":"error",...,"error":{"name":"UnknownError","data":{"message":"\"Streaming response failed\""}}}.
// That shape carries no isRetryable field, so string matching — not the
// structural signal — is what recognizes it.
const TRANSPORT_MARKERS = [
  "streaming response failed",
  "socket hang up",
  "econnreset",
  "econnaborted",
  "fetch failed",
  "premature close",
];

// This exact phrase is generated by THIS codebase itself (cliAgentRunner.ts's
// argv-prompt-size guard), never by a vendor CLI's own output, so — unlike
// the bare "exceeded" text isQuotaError deliberately excludes above — it can
// be matched narrowly and safely: nothing else can produce it. A prompt that
// is too large for one provider's argv-only transport (e.g. Kimi's `-p`,
// which has no stdin/file input at all — see providers.ts) is a structural
// limit of THAT provider, not a transient blip, but the same cascade that
// already exists for quota/temporary-unavailable failures is exactly the
// right response: a different backup provider very likely has a higher (or
// no) prompt-size ceiling, so trying it is safe and often succeeds outright.
const PROVIDER_PROMPT_TOO_LARGE_MARKER = "prompt is too large for this cli mode";

// Authentication failures are terminal for the selected provider. Keep this
// deliberately broad: providers often label expired credentials as generic
// unavailability (or even "try again later"-style transient wording) rather
// than a clean 401/403, so a narrow match would auto-fallback to the backup
// model on what is actually an auth problem — exactly what callers must
// never do. Exported for direct unit testing.
export function isAuthenticationFailure(message: string | undefined): boolean {
  const value = message ?? "";
  if (/not\s+installed|command\s+not\s+found|could\s+not\s+start\b/i.test(value)) {
    return false;
  }
  // "session"/"token" tolerate a short word gap (e.g. "session has timed
  // out", "token has been revoked") instead of requiring the state word to
  // sit directly next to the noun.
  return /sign[\s-]*in|log(?:ged|ging)?[\s-]*(?:in|out)|session(?:\s+\w+){0,3}\s+(?:expired|invalid|missing|timed?\s*out)|authenticat\w*|authoris\w*|authoriz\w*|credential|re[-\s]?auth\w*|token(?:\s+\w+){0,3}\s+(?:expired|invalid|missing|revoked)|api\s*key|access\s*denied|permission\s*denied|forbidden|unauthori[sz]ed|\b(?:401|403)\b/i.test(value);
}

/**
 * `structuredSignal` is an OR'd-in, provider-scoped structural verdict (e.g.
 * claude-cli's stream-json `result` event carrying `error: "rate_limit"` —
 * see extractClaudeCliStructuredDiagnostics in cliAgentRunner.ts) that a
 * caller has already determined, independent of any text. It exists because
 * a structured error CODE (underscored, like "rate_limit") does not
 * necessarily contain any of QUOTA_MARKERS' phrase spellings ("rate limit"
 * with a space, "ratelimit" with none) as a literal substring, so relying on
 * the phrase scan alone would miss it. The phrase-based scan below still
 * runs unconditionally — this is an ADDITIONAL signal, never a replacement,
 * so free-text quota phrasing from providers with no structural signal at
 * all keeps working exactly as before.
 */
export function isQuotaError(
  message: string | undefined,
  structuredSignal?: boolean
): boolean {
  if (structuredSignal === true) {
    return true;
  }
  const value = (message ?? "").toLowerCase();
  return QUOTA_MARKERS.some((marker) => value.includes(marker));
}

/**
 * True when a failure message describes a transport-level drop rather than a
 * refusal. Such failures are recoverable by retrying or by switching to
 * another model, so they must not be classified "generic" — see classifyFailure.
 */
export function isTransportError(message: string | undefined): boolean {
  const value = (message ?? "").toLowerCase();
  return TRANSPORT_MARKERS.some((marker) => value.includes(marker));
}

export function classifyFailure<T extends { errorMessage?: string; authDiagnosticText?: string; structuredQuotaSignal?: boolean }>(result: T): T & { failureKind: "quota" | "temporarily-unavailable" | "generic" } {
  const message = (result.errorMessage ?? "").toLowerCase();
  // Quota first: a rate-limited request whose stream also dropped is a quota
  // event, and reporting it as a transport blip would retry straight back into
  // the same limit.
  //
  // TEMPORARY_MARKERS may not promote a message that is ALSO an
  // authentication failure: the text-mode cascade gate (runnerRegistry.ts)
  // keys on failureKind alone with no auth check of its own (unlike the
  // implementation-mode gate, which separately consults authFailure before
  // ever looking at this classification), so a credentials/entitlement
  // message that happens to also read "service unavailable" would otherwise
  // cascade through every configured backup model there — exactly what must
  // never happen for an auth failure. Quota's own markers are left ungated:
  // they are quota-specific vocabulary that does not plausibly overlap with
  // an auth message, and a rate-limited request must keep classifying as
  // quota regardless.
  //
  // TRANSPORT_MARKERS is deliberately NOT checked here, even though it once
  // was: this function is shared with Copilot's own failure classification
  // and has no provider context, so it cannot tell a structured-stream CLI
  // (opencode, whose diagnostic text is scoped to parsed error events) from
  // an opaque one (kiro-cli, codex-cli, whose diagnostic text IS raw
  // stdout/model prose) — a distinction that matters enormously for whether
  // a transport-phrase match is trustworthy. See applyTransportTransience
  // (cliAgentRunner.ts), which has that provider context and applies
  // TRANSPORT_MARKERS there instead, scoped accordingly.
  // Prefers authDiagnosticText over errorMessage, mirroring runnerRegistry.ts's
  // own auth check: on the CLI path errorMessage may already have the
  // provider's login hint appended (see toFriendlyError in cliAgentRunner.ts),
  // and that hint text itself contains phrases ("log in", "API key") that
  // isAuthenticationFailure matches — so scanning errorMessage directly would
  // let an appended hint re-confirm the very auth verdict that produced it.
  // authDiagnosticText is absent for non-CLI callers (e.g. Copilot), which
  // fall back to errorMessage exactly as before.
  const isAuth = isAuthenticationFailure(result.authDiagnosticText ?? result.errorMessage);
  const failureKind = isQuotaError(result.errorMessage, result.structuredQuotaSignal)
    ? "quota" as const
    : !isAuth && (
        TEMPORARY_MARKERS.some(m => message.includes(m)) ||
        message.includes(PROVIDER_PROMPT_TOO_LARGE_MARKER)
      )
      ? "temporarily-unavailable" as const
      : "generic" as const;
  return { ...result, failureKind };
}

export function classifyCliFailure<T extends { status: "completed" | "failed" | "cancelled"; errorMessage?: string; authDiagnosticText?: string }>(result: T): T & { failureKind: "quota" | "temporarily-unavailable" | "generic" } {
  return classifyFailure(result);
}

export async function savePendingResume(context: vscode.ExtensionContext, request: AgentRunRequest): Promise<void> {
  const existing = context.workspaceState.get<PendingResumeOperation>(KEY);
  const next: PendingResumeOperation = {
    request: { stage: request.stage, prompt: request.prompt, modelId: request.modelId, taskFolderPath: request.taskFolderUri.fsPath, workspacePath: request.workspaceUri.fsPath, outputFilePath: request.outputFile.fsPath },
    attempts: existing?.request.prompt === request.prompt ? existing.attempts + 1 : 0,
    createdAt: new Date().toISOString(),
  };
  await context.workspaceState.update(KEY, next);
}

export function getPendingResume(context: vscode.ExtensionContext): PendingResumeOperation | undefined {
  return context.workspaceState.get<PendingResumeOperation>(KEY);
}

export async function clearPendingResume(context: vscode.ExtensionContext): Promise<void> { await context.workspaceState.update(KEY, undefined); }

export async function handleQuotaFailure(context: vscode.ExtensionContext, request: AgentRunRequest, result: AgentRunResult, switchModel?: () => Thenable<void>): Promise<"resume" | "switch" | undefined> {
  if (result.failureKind !== "quota") {
    return undefined;
  }
  await savePendingResume(context, request);
  notifyDesktop("Ensemble — question", "AI credits are exhausted. Resume when they restore, or switch model?");
  taskOperations.report(request.taskFolderUri.fsPath, "waiting for your answer — credits exhausted");
  // The run cannot proceed at all without this choice — swap the row's
  // spinner for the "waiting for you" indicator so it doesn't read as
  // background work quietly making progress.
  taskOperations.setWaitingForUser(request.taskFolderUri.fsPath, true);
  // Also route into the internal Notifications panel as a terminal/error
  // record (per severity policy: exhausted credits block the run). The
  // interactive choice itself must stay a real modal below — "Resume" vs
  // "Switch model" are genuine alternative actions the caller branches on.
  NotificationRouter.showError("AI credits are exhausted. Can't proceed without your input — resume when credits restore, or switch model.");
  const choice = await vscode.window.showWarningMessage("AI credits are exhausted.", "Resume when credits restore", "Switch model");
  taskOperations.report(request.taskFolderUri.fsPath, undefined);
  taskOperations.setWaitingForUser(request.taskFolderUri.fsPath, false);
  if (choice === "Switch model") { await switchModel?.(); return "switch"; }
  return choice === "Resume when credits restore" ? "resume" : undefined;
}

// ─── Session-observed quota status ──────────────────────────────────────────
//
// No provider exposes a numeric "percent of quota remaining" through its
// discovery/CLI surface, so a fabricated percentage would just be a made-up
// number (see the settings webview's explicit "never present fabricated
// usage data" comment). What we *can* report honestly is what this session
// has actually observed: the most recent run for a given stage+model either
// completed/failed for a non-quota reason ("ok"), or failed because the
// provider reported quota/rate-limit exhaustion ("exhausted"). This is reset
// each time the extension host restarts — it is a live signal, not a
// persisted ledger.

export type QuotaState = "ok" | "exhausted" | "unavailable";

export interface QuotaObservation {
  state: QuotaState;
  observedAt: string;
  /** Only present when the provider explicitly reported a percentage. */
  remainingPercent?: number;
}

const quotaObservations = new Map<string, QuotaObservation>();

function quotaKey(stage: TaskStage, modelId: string | undefined): string {
  return `${stage}::${modelId ?? "(default)"}`;
}

/**
 * Record what a completed run revealed about a stage+model's quota state.
 * Called after every run that has a `failureKind` classification (quota or
 * generic) or completed successfully — anything other than "quota" means the
 * provider was reachable and not currently blocked by quota exhaustion.
 */
export function recordQuotaObservation(
  stage: TaskStage,
  modelId: string | undefined,
  failureKind: "quota" | "temporarily-unavailable" | "generic" | undefined,
  errorMessage?: string
): void {
  const percentMatch = /(?:remaining|left|available)[^\d]{0,12}(\d{1,3})\s*%/i.exec(errorMessage ?? "");
  const parsedPercent = percentMatch ? Number(percentMatch[1]) : undefined;
  quotaObservations.set(quotaKey(stage, modelId), {
    state: failureKind === "quota" ? "exhausted" : failureKind === "temporarily-unavailable" ? "unavailable" : "ok",
    observedAt: new Date().toISOString(),
    ...(parsedPercent !== undefined && parsedPercent <= 100 ? { remainingPercent: parsedPercent } : {}),
  });
}

export function getQuotaObservation(
  stage: TaskStage,
  modelId: string | undefined
): QuotaObservation | undefined {
  return quotaObservations.get(quotaKey(stage, modelId));
}

/** Human-readable status for the settings webview. Never fabricates a number. */
export function formatQuotaStatus(observation: QuotaObservation | undefined): string {
  if (!observation) {
    return "No usage observed yet this session";
  }
  const time = new Date(observation.observedAt).toLocaleTimeString();
  const percent = observation.remainingPercent === undefined ? "" : ` (${observation.remainingPercent}% remaining)`;
  return observation.state === "exhausted"
    ? `Quota exhausted as of ${time}${percent}`
    : observation.state === "unavailable"
      ? `Unavailable as of ${time}`
    : `OK as of ${time}${percent}`;
}

export function getQuotaStatusText(stage: TaskStage, modelId: string | undefined): string {
  if (!modelId) {
    return "-";
  }
  return formatQuotaStatus(getQuotaObservation(stage, modelId));
}

/** Tooltip paired with getQuotaStatusText's "-" placeholder vs. observed text. */
export function getQuotaStatusTooltip(modelId: string | undefined): string {
  if (!modelId) {
    return "No model configured for this slot — usage cannot be observed.";
  }
  return "Session-observed usage status, not a live percentage (no provider exposes numeric quota remaining).";
}

export const __quotaTestOnly = {
  clear(): void {
    quotaObservations.clear();
  },
  /**
   * Directly set an observation with an arbitrary `observedAt`, bypassing
   * recordQuotaObservation's "now" timestamp — needed to test callers that
   * gate on observation recency (e.g. runAiToFile's backup-skip check in
   * reviewActions.ts) against an observation old enough that it should no
   * longer apply, which the public recording API can't produce on demand.
   */
  setObservation(
    stage: TaskStage,
    modelId: string | undefined,
    observation: QuotaObservation
  ): void {
    quotaObservations.set(quotaKey(stage, modelId), observation);
  },
};
