#!/usr/bin/env node
/**
 * One-time generator for the immutable pre-gate production-source snapshot
 * (plan "Repository-contained Phase 0", AC-BASE-01/02).
 *
 * WHY THIS IS SEPARATE FROM resolveProductionSourceUniverse.mjs
 * ----------------------------------------------------------------
 * The regular resolver answers "what does the CURRENT working tree ship".
 * This script answers a different, one-time question: "what did the
 * production source universe look like at the commit that predates this
 * plan's own changes" — the frozen reference point every later addition or
 * removal must be justified against (plan §1.5-style annotations, applied
 * here to source files instead of routes). It checks out that historical
 * commit into an isolated `git worktree` (never the working tree — nothing
 * here touches uncommitted changes) and runs the SAME scan rules
 * (scripts/lib/productionSourceScan.mjs) against that snapshot, using the
 * CURRENT repo's node_modules/esbuild/typescript for tooling.
 *
 * Build options at the pre-gate ref are assumed identical to today's shared
 * `esbuild.config.js` factory (verified true for the default ref by `git
 * diff` at the time this script was written: the factory was a byte-for-byte
 * extraction of what was previously inlined in esbuild.js). This script
 * re-verifies that assumption at run time with a substring sanity check
 * against the historical esbuild.js before trusting it, rather than quietly
 * relying on a comment staying true forever.
 *
 * This script REFUSES to overwrite an existing pre-gate snapshot. That file
 * is immutable once written; if it is ever legitimately wrong, delete it
 * explicitly and re-run rather than adding a force flag here.
 *
 * USAGE
 * -----
 *   node scripts/generatePregateProductionSourceBaseline.mjs [gitRef]
 *
 * `gitRef` defaults to PREGATE_GIT_REF below — the last commit before this
 * plan's changes began landing in this worktree.
 */

import { createRequire } from "module";
import { execFileSync } from "child_process";
import fs from "fs";
import os from "os";
import path from "path";
import { fileURLToPath } from "url";
import { sha256OfFile, scanBundledSources, classifyNonBundledAssets, TEST_LIKE_PATTERNS } from "./lib/productionSourceScan.mjs";

const require = createRequire(import.meta.url);
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");

/** The commit immediately before this plan's changes started landing in this worktree ("0.64.2"). */
const PREGATE_GIT_REF = "bdced3e";

const PREGATE_PATH = path.join(repoRoot, "workflow-inventories", "workflow-production-source-pregate-v1.json");

/** Build-option fragments that must appear verbatim in the historical esbuild.js for the reuse-current-factory assumption to hold. */
const REQUIRED_HISTORICAL_BUILD_OPTION_FRAGMENTS = [
  'entryPoints: ["src/extension.ts"]',
  "bundle: true",
  'format: "cjs"',
  'platform: "node"',
  'outfile: "dist/extension.js"',
  'external: ["vscode"]',
];

function git(args, cwd = repoRoot) {
  return execFileSync("git", args, { cwd, encoding: "utf8" });
}

async function main() {
  const gitRef = process.argv[2] || PREGATE_GIT_REF;

  if (fs.existsSync(PREGATE_PATH)) {
    console.error(
      `✘ ${path.relative(repoRoot, PREGATE_PATH)} already exists. The pre-gate snapshot is immutable — delete it ` +
        `explicitly first if you are certain it must be regenerated (this should essentially never happen).`
    );
    process.exitCode = 1;
    return;
  }

  const resolvedSha = git(["rev-parse", gitRef]).trim();
  console.log(`Generating pre-gate snapshot from ${gitRef} (${resolvedSha})...`);

  const worktreePath = path.join(os.tmpdir(), `ensemble-pregate-${process.pid}-${resolvedSha.slice(0, 12)}`);
  fs.rmSync(worktreePath, { recursive: true, force: true });

  // core.autocrlf=false: materialize verbatim blob bytes so recorded digests
  // are independent of the generating machine's checkout profile. Digests
  // are additionally canonical (LF-normalized for text — see
  // scripts/lib/productionSourceScan.mjs), so a snapshot generated by any
  // machine describes the same tree identically. The ORIGINAL committed
  // snapshot predates both safeguards and recorded raw CRLF-smudged bytes
  // for some rows; it stays immutable, and the resolver's tolerant matcher
  // (contentMatchesRecordedSha256) absorbs exactly that line-ending skew.
  git(["-c", "core.autocrlf=false", "worktree", "add", "--detach", "--force", worktreePath, resolvedSha]);
  try {
    const historicalPackageJsonPath = path.join(worktreePath, "package.json");
    if (!fs.existsSync(historicalPackageJsonPath)) {
      throw new Error(`${resolvedSha} has no package.json at its root — cannot resolve build options.`);
    }
    const historicalPackageJson = JSON.parse(fs.readFileSync(historicalPackageJsonPath, "utf8"));

    const historicalEsbuildJsPath = path.join(worktreePath, "esbuild.js");
    const historicalEsbuildJs = fs.existsSync(historicalEsbuildJsPath)
      ? fs.readFileSync(historicalEsbuildJsPath, "utf8")
      : "";
    const missingFragments = REQUIRED_HISTORICAL_BUILD_OPTION_FRAGMENTS.filter(
      (fragment) => !historicalEsbuildJs.includes(fragment)
    );
    if (missingFragments.length > 0) {
      throw new Error(
        `${resolvedSha}:esbuild.js does not contain the expected build-option fragment(s): ` +
          `${missingFragments.join(", ")}. This script's assumption that build options at the pre-gate ref match ` +
          `today's esbuild.config.js factory no longer holds for this ref and must be re-verified by hand ` +
          `(re-derive historical options explicitly) before trusting a generated snapshot.`
      );
    }

    const esbuild = require(path.join(repoRoot, "node_modules", "esbuild"));
    const { createProductionBuildOptions, createEsbuildProblemMatcherPlugin } = require(
      path.join(repoRoot, "esbuild.config.js")
    );

    const { firstPartyInputs } = await scanBundledSources({
      sourceRoot: worktreePath,
      toolingRoot: repoRoot,
      esbuild,
      createProductionBuildOptions,
      plugins: [createEsbuildProblemMatcherPlugin({ quiet: true })],
    });

    const testLikeReachable = firstPartyInputs.filter((p) => TEST_LIKE_PATTERNS.some((re) => re.test(p)));
    if (testLikeReachable.length > 0) {
      throw new Error(
        `${resolvedSha} reaches test/fixture files from its production entrypoint: ${testLikeReachable.join(", ")}`
      );
    }

    const fileDigests = firstPartyInputs
      .map((relPath) => ({ path: relPath, sha256: sha256OfFile(path.join(worktreePath, relPath)) }))
      .sort((a, b) => a.path.localeCompare(b.path));

    const { assets: shippedAssets, missing } = classifyNonBundledAssets({
      sourceRoot: worktreePath,
      packageJson: historicalPackageJson,
    });
    if (missing.length > 0) {
      throw new Error(`Missing contribution/resource assets at ${resolvedSha}: ${missing.join("; ")}`);
    }

    const pregate = {
      schemaVersion: 1,
      generatedBy: "scripts/generatePregateProductionSourceBaseline.mjs",
      description:
        "IMMUTABLE pre-gate production source universe, frozen at the commit that predates this plan's own " +
        "changes. Never regenerated by resolveProductionSourceUniverse.mjs. Every file added to, removed from, " +
        "or modified (content digest changed) since this snapshot must be recorded in " +
        "workflow-production-source-annotations-v1.json.",
      pregateGitRef: gitRef,
      pregateGitSha: resolvedSha,
      packageName: historicalPackageJson.name,
      packageVersion: historicalPackageJson.version,
      fileCount: fileDigests.length,
      files: fileDigests,
      shippedAssets,
    };

    fs.mkdirSync(path.dirname(PREGATE_PATH), { recursive: true });
    fs.writeFileSync(PREGATE_PATH, JSON.stringify(pregate, null, 2) + "\n", "utf8");
    console.log(
      `✓ Wrote immutable pre-gate snapshot with ${fileDigests.length} source file(s) and ${shippedAssets.length} ` +
        `shipped asset(s) to ${path.relative(repoRoot, PREGATE_PATH)}`
    );
  } finally {
    git(["worktree", "remove", "--force", worktreePath]);
  }
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
