#!/usr/bin/env node
/**
 * Production source-universe resolver (plan §1.1, Executable Order step 1).
 *
 * WHY THIS EXISTS
 * ---------------
 * Later plan cohorts (route inventory, path-consumer inventory, LM-boundary
 * proof) all need one immutable answer to "what ships in the packaged
 * extension" that cannot silently drift from what actually ships. Deriving
 * that set from `tsconfig.json`'s broad `include` would pull in
 * `src/test/**`, fixtures, and dev-only harnesses that never reach a user.
 *
 * This script runs the SAME bundler options `esbuild.js` uses to produce
 * `dist/extension.js` — via the shared `esbuild.config.js` factory, so the
 * two builds cannot drift from each other (AC-BASE-03) — but in
 * no-write/metafile mode, and reads the resulting dependency graph for the
 * TS/JS bundle. It separately classifies the two shipped-but-not-bundled
 * asset categories this extension actually has: contribution-referenced
 * images (package.json `icon` / `contributes` fields, e.g. the marketplace
 * icon and view/command icons) and the `resources/prompts/*.md` templates
 * read at runtime via `vscode.workspace.fs.readFile` (never statically
 * importable, so esbuild's graph can never see them) — see
 * scripts/lib/productionSourceScan.mjs for both rules. Every file physically
 * present under `images/**` or `resources/**` must be accounted for by one
 * of those two rules or verification fails closed (plan §1.1 point 6).
 *
 * IMMUTABILITY (plan "Repository-contained Phase 0" + AC-BASE-01/02)
 * --------------------------------------------------------------------
 * `workflow-production-source-pregate-v1.json` is the immutable pre-gate
 * snapshot, generated exactly once by
 * `scripts/generatePregateProductionSourceBaseline.mjs` against the commit
 * that predates this plan's own changes, and never regenerated by this
 * script. Every file this run finds that is NOT in that frozen snapshot
 * (added or removed), AND every file present in both snapshots whose content
 * digest changed (modified in place), must have a matching entry in
 * `workflow-production-source-annotations-v1.json` recording its cohort and
 * rationale — undocumented drift from the immutable baseline fails closed,
 * rather than being silently absorbed by `--generate` the way the prior
 * version of this script allowed (the exact gap the implementation review
 * identified: "the checked baseline already includes step 2-4 production
 * files" with no recorded evidence for that drift, and separately, "modified
 * baseline digests are not evidence-gated").
 *
 * `workflow-production-source-baseline-v1.json` remains the regenerable,
 * currently-accepted snapshot (`--generate` rewrites it) — but `--generate`
 * itself now refuses to run while undocumented pregate drift exists, so it
 * can no longer be used to launder unannotated changes into "the baseline".
 * `workflow-production-source-live-v1.json` is regenerated unconditionally
 * every run, for informational diffing.
 *
 * USAGE
 * -----
 *   node scripts/resolveProductionSourceUniverse.mjs           # verify (default)
 *   node scripts/resolveProductionSourceUniverse.mjs --generate # (re)write the checked-in baseline
 */

import { createRequire } from "module";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import {
  sha256OfFile,
  sha256OfText,
  canonicalContentSha256,
  contentMatchesRecordedSha256,
  fileMatchesRecordedSha256,
  TEST_LIKE_PATTERNS,
  scanBundledSources,
  classifyNonBundledAssets,
} from "./lib/productionSourceScan.mjs";
import { verifyFixtureProvenance } from "./lib/fixtureProvenance.mjs";

const require = createRequire(import.meta.url);
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");

const esbuild = require("esbuild");
const { createProductionBuildOptions, createEsbuildProblemMatcherPlugin } = require(
  path.join(repoRoot, "esbuild.config.js")
);
const packageJson = require(path.join(repoRoot, "package.json"));

const INVENTORY_DIR = path.join(repoRoot, "workflow-inventories");
const EOL_FIXTURE_PATH = path.join(
  repoRoot,
  "test-fixtures",
  "workflow-production-sources",
  "eol-digest-fixture-v1.json"
);
const PREGATE_PATH = path.join(INVENTORY_DIR, "workflow-production-source-pregate-v1.json");
const BASELINE_PATH = path.join(INVENTORY_DIR, "workflow-production-source-baseline-v1.json");
const LIVE_PATH = path.join(INVENTORY_DIR, "workflow-production-source-live-v1.json");
const ANNOTATIONS_PATH = path.join(INVENTORY_DIR, "workflow-production-source-annotations-v1.json");
const GENERATED_SOURCES_PATH = path.join(INVENTORY_DIR, "workflow-production-generated-sources-v1.json");

/**
 * Naming conventions that mark a path as a generated output. Any bundle
 * input or shipped asset matching one of these must be declared in
 * workflow-production-generated-sources-v1.json (plan §1.1 point 7) — the
 * manifest-backed check, not a comment, is what fails closed.
 */
const GENERATED_LIKE_PATTERNS = [
  /\.generated\./i,
  /\.gen\.[cm]?[jt]sx?$/i,
  /(^|\/)dist\//,
  /(^|\/)out\//,
  /(^|\/)__generated__\//,
];

const SHA256_RE = /^[0-9a-f]{64}$/;
const KNOWN_COHORTS = new Set([
  "baseline", "safety", "lmIsolation", "runnerV1", "foundations", "privacy", "chat",
  "text1", "text2", "text3", "lifecycle", "creation", "resume", "edit", "git", "cleanup", "nonPlan",
]);

function toRepoRelativePosix(absPath) {
  return path.relative(repoRoot, absPath).split(path.sep).join("/");
}

/** Fails the run; every failure here is a hard stop, never a warning. */
function fail(message) {
  console.error(`✘ [resolveProductionSourceUniverse] ${message}`);
  process.exitCode = 1;
}

/**
 * Loads the annotation file and structurally validates every entry against
 * the full §1.5-style evidence contract (owner, expiry cohort, evidence
 * digests). Structural problems are reported through `record` so they fail
 * the run rather than degrading to "annotation exists, good enough".
 */
function loadAnnotations(record) {
  if (!fs.existsSync(ANNOTATIONS_PATH)) {
    return null;
  }
  const parsed = JSON.parse(fs.readFileSync(ANNOTATIONS_PATH, "utf8"));
  const byKey = new Map();
  for (const entry of parsed.annotations || []) {
    const label = `${entry.disposition}:${entry.path}`;
    for (const field of ["path", "disposition", "cohort", "planSection", "rationale", "owner", "expiryCohort"]) {
      if (typeof entry[field] !== "string" || entry[field].length === 0) {
        record(`Annotation ${label} is missing required field "${field}" (workflow-production-source-annotations-v1.schema.json).`);
      }
    }
    if (!KNOWN_COHORTS.has(entry.cohort)) {
      record(`Annotation ${label} has unknown cohort ${JSON.stringify(entry.cohort)}.`);
    }
    if (!KNOWN_COHORTS.has(entry.expiryCohort)) {
      record(`Annotation ${label} has unknown expiryCohort ${JSON.stringify(entry.expiryCohort)}.`);
    }
    const evidence = entry.evidence;
    if (typeof evidence !== "object" || evidence === null) {
      record(`Annotation ${label} is missing its required "evidence" object.`);
    } else {
      if ((entry.disposition === "added" || entry.disposition === "modified") && !SHA256_RE.test(evidence.liveSha256 || "")) {
        record(`Annotation ${label} must carry evidence.liveSha256 (sha256 of the content its rationale was written against).`);
      }
      if (entry.disposition === "removed" && !SHA256_RE.test(evidence.pregateSha256 || "")) {
        record(`Annotation ${label} must carry evidence.pregateSha256 (the removed path's digest in the pre-gate snapshot).`);
      }
      // A "removed" row has no live content, so evidence.liveSha256 (if present) is never
      // read or compared by this script — it would read as evidence but function as
      // decoration, exactly the kind of unverified checked-in claim this file exists to
      // rule out. Only evidence.pregateSha256 applies to removed rows.
      if (entry.disposition === "removed" && typeof evidence?.liveSha256 === "string" && evidence.liveSha256.length > 0) {
        record(
          `Annotation ${label} carries evidence.liveSha256, but a "removed" disposition has no live content to check ` +
            `it against and this script never reads liveSha256 for removed rows. Delete the field — only ` +
            `evidence.pregateSha256 applies to removed rows.`
        );
      }
      // Plan §1.5: every annotation carries exact span, symbol, edge kind,
      // and target action key — descriptive evidence is mandatory, not
      // optional, so a bare digest can never stand in for a reviewed claim
      // about WHAT changed and WHERE it routes.
      for (const field of ["symbol", "sourceSpan", "edgeKind", "targetActionKey"]) {
        if (typeof evidence[field] !== "string" || evidence[field].length === 0) {
          record(
            `Annotation ${label} must carry evidence.${field} (plan §1.5 evidence contract — ` +
              `workflow-production-source-annotations-v1.schema.json).`
          );
        }
      }
    }
    byKey.set(label, entry);
  }
  return byKey;
}

/**
 * Digest-portability self-check (implementation-review fixture): proves on
 * every run — from checked-in fixture vectors that git EOL settings cannot
 * rewrite (base64) — that the LF and CRLF representations of the same text
 * produce the identical canonical digest, that genuinely different text does
 * not, that the pre-gate tolerant matcher accepts a historical raw digest
 * recorded from either single-EOL form, and that binary content (NUL-bearing,
 * with embedded 0x0D0A) is hashed verbatim rather than normalized. If the
 * canonicalization in scripts/lib/productionSourceScan.mjs ever regresses to
 * checkout-dependent hashing, this fails closed before any evidence is
 * compared.
 */
function verifyEolDigestPortabilityFixture(record) {
  if (!fs.existsSync(EOL_FIXTURE_PATH)) {
    record(
      `Missing digest-portability fixture ${toRepoRelativePosix(EOL_FIXTURE_PATH)} — it proves canonical digests are ` +
        `line-ending-independent and must exist for production-source evidence to be trusted.`
    );
    return;
  }
  const fixture = JSON.parse(fs.readFileSync(EOL_FIXTURE_PATH, "utf8"));
  const lf = Buffer.from(fixture.text.lfBase64, "base64");
  const crlf = Buffer.from(fixture.text.crlfBase64, "base64");
  const mutated = Buffer.from(fixture.text.mutatedBase64, "base64");
  const binary = Buffer.from(fixture.binary.bytesBase64, "base64");

  if (canonicalContentSha256(lf) !== fixture.text.canonicalSha256) {
    record(`EOL fixture: canonical digest of the LF text form does not match the recorded canonicalSha256.`);
  }
  if (canonicalContentSha256(crlf) !== fixture.text.canonicalSha256) {
    record(
      `EOL fixture: canonical digest of the CRLF text form does not match the LF form — canonical digests have ` +
        `regressed to checkout-line-ending-dependent hashing.`
    );
  }
  if (canonicalContentSha256(mutated) === fixture.text.canonicalSha256) {
    record(`EOL fixture: mutated text unexpectedly matches the canonical digest — digesting is not content-sensitive.`);
  }
  if (!contentMatchesRecordedSha256(lf, fixture.text.crlfRawSha256)) {
    record(`EOL fixture: tolerant matcher rejected a historical CRLF-form raw digest for LF content.`);
  }
  if (!contentMatchesRecordedSha256(crlf, fixture.text.lfRawSha256)) {
    record(`EOL fixture: tolerant matcher rejected a historical LF-form raw digest for CRLF content.`);
  }
  if (contentMatchesRecordedSha256(mutated, fixture.text.lfRawSha256)) {
    record(`EOL fixture: tolerant matcher accepted genuinely different text — it must only absorb line-ending drift.`);
  }
  if (canonicalContentSha256(binary) !== fixture.binary.rawSha256) {
    record(
      `EOL fixture: binary content (NUL-bearing, with embedded CRLF bytes) was not hashed verbatim — binary blobs ` +
        `must never be line-ending-normalized.`
    );
  }
}

async function main() {
  const generate = process.argv.includes("--generate");
  const failures = [];
  const record = (message) => {
    failures.push(message);
    fail(message);
  };

  verifyEolDigestPortabilityFixture(record);
  // Fixture-provenance gate (plan §3.10's checked-in evidence-base rule,
  // extended to this tree per the implementation review): every fixture the
  // digest-portability checks rest on must carry a README row recording what
  // it proves, bidirectionally and fail-closed, on every verify and generate
  // run — so a fixture cannot be added or dropped without its record.
  verifyFixtureProvenance({
    repoRoot,
    fixturesDir: path.join(repoRoot, "test-fixtures", "workflow-production-sources"),
    fixtureFileRe: /\.json$/,
    fixtureFileDescription: ".json",
    layout: "flat",
    record,
  });

  // --- package.json.main + build configuration ---------------------------
  const buildOptions = createProductionBuildOptions({ production: true });
  const declaredMain = packageJson.main;
  const normalizedMain = declaredMain.replace(/^\.\//, "");
  const normalizedOutfile = buildOptions.outfile.replace(/^\.\//, "");

  if (normalizedMain !== normalizedOutfile) {
    record(
      `package.json "main" (${declaredMain}) does not match the shared build config's outfile (${buildOptions.outfile}). ` +
        `The packaged extension entry and the resolved production build must be the same file.`
    );
  }
  if (buildOptions.entryPoints.length !== 1 || buildOptions.entryPoints[0] !== "src/extension.ts") {
    record(
      `Shared build config entryPoints must be exactly ["src/extension.ts"], got ${JSON.stringify(buildOptions.entryPoints)}.`
    );
  }

  // --- bundled TS/JS sources -----------------------------------------------
  const { firstPartyInputs } = await scanBundledSources({
    sourceRoot: repoRoot,
    toolingRoot: repoRoot,
    esbuild,
    createProductionBuildOptions,
    plugins: [createEsbuildProblemMatcherPlugin({ quiet: true })],
  });

  const testLikeReachable = firstPartyInputs.filter((p) => TEST_LIKE_PATTERNS.some((re) => re.test(p)));
  if (testLikeReachable.length > 0) {
    record(
      `${testLikeReachable.length} test/fixture/harness file(s) are reachable from the production entrypoint: ` +
        testLikeReachable.join(", ")
    );
  }

  const KNOWN_NON_SOURCE_INPUTS = new Set(["package.json"]);
  const nonSourceExtensions = firstPartyInputs
    .filter((p) => !/\.[cm]?[jt]sx?$/i.test(p))
    .filter((p) => !KNOWN_NON_SOURCE_INPUTS.has(p));
  if (nonSourceExtensions.length > 0) {
    record(
      `${nonSourceExtensions.length} non-TS/JS first-party input(s) are reachable from the production entrypoint but are ` +
        `not the one documented exception (package.json): ` + nonSourceExtensions.join(", ")
    );
  }

  const sortedFiles = [...new Set(firstPartyInputs)].sort((a, b) => a.localeCompare(b));
  const fileDigests = sortedFiles.map((relPath) => ({
    path: relPath,
    sha256: sha256OfFile(path.join(repoRoot, relPath)),
  }));

  // --- non-bundled shipped assets: contribution icons + runtime resource
  // copies (plan §1.1 point 6). Every file physically under images/** or
  // resources/** must be accounted for by one of the two rules. ------------
  const { assets: shippedAssets, missing: missingAssets, unaccounted: unaccountedAssets } = classifyNonBundledAssets({
    sourceRoot: repoRoot,
    packageJson,
  });
  for (const message of missingAssets) {
    record(message);
  }
  if (unaccountedAssets.length > 0) {
    record(
      `${unaccountedAssets.length} file(s) under images/** or resources/** are not referenced by any package.json ` +
        `contribution/icon field and do not match the resources/prompts/*.md runtime-copy rule: ` +
        unaccountedAssets.join(", ")
    );
  }

  // --- generated production sources (plan §1.1 point 7): manifest-backed
  // enforcement, both directions. Every declared generated source must
  // exist, digest-match, and actually be part of the resolved universe; and
  // every resolved input/asset matching a generated-output naming
  // convention must be declared. ------------------------------------------
  const resolvedUniversePaths = new Set([
    ...sortedFiles,
    ...shippedAssets.map((a) => a.path),
  ]);
  if (!fs.existsSync(GENERATED_SOURCES_PATH)) {
    record(
      `Missing generated-source manifest ${toRepoRelativePosix(GENERATED_SOURCES_PATH)} (plan §1.1 point 7). ` +
        `It must exist (with an empty "generatedSources" list if the build has no generated inputs).`
    );
  } else {
    const manifest = JSON.parse(fs.readFileSync(GENERATED_SOURCES_PATH, "utf8"));
    const declaredGenerated = new Set();
    for (const entry of manifest.generatedSources || []) {
      const entryLabel = `generated source ${JSON.stringify(entry.outputPath)}`;
      for (const field of ["outputPath", "generatorCommand", "sha256"]) {
        if (typeof entry[field] !== "string" || entry[field].length === 0) {
          record(`${entryLabel} is missing required field "${field}" in ${toRepoRelativePosix(GENERATED_SOURCES_PATH)}.`);
        }
      }
      if (!Array.isArray(entry.sourceInputs)) {
        record(`${entryLabel} must declare its "sourceInputs" array in ${toRepoRelativePosix(GENERATED_SOURCES_PATH)}.`);
      }
      if (typeof entry.outputPath === "string") {
        declaredGenerated.add(entry.outputPath);
        const absPath = path.join(repoRoot, entry.outputPath);
        if (!fs.existsSync(absPath)) {
          record(`${entryLabel} is declared but does not exist on disk.`);
        } else if (sha256OfFile(absPath) !== entry.sha256) {
          record(`${entryLabel} content does not match its declared sha256 — regenerate it and update the manifest.`);
        }
        if (!resolvedUniversePaths.has(entry.outputPath)) {
          record(
            `${entryLabel} is declared but is not part of the resolved production universe — remove the stale entry ` +
              `or fix the build reference.`
          );
        }
      }
    }
    const undeclaredGenerated = [...resolvedUniversePaths]
      .filter((p) => GENERATED_LIKE_PATTERNS.some((re) => re.test(p)))
      .filter((p) => !declaredGenerated.has(p))
      .sort((a, b) => a.localeCompare(b));
    if (undeclaredGenerated.length > 0) {
      record(
        `${undeclaredGenerated.length} production input(s) match a generated-output naming convention but are not ` +
          `declared in ${toRepoRelativePosix(GENERATED_SOURCES_PATH)}: ${undeclaredGenerated.join(", ")}`
      );
    }
  }

  const lockfilePath = path.join(repoRoot, "pnpm-lock.yaml");
  const buildOptionsDigest = sha256OfText(JSON.stringify(buildOptions));

  /** path -> sha256, merging bundled sources and shipped assets (both carry a digest). */
  const digestsByPath = new Map([
    ...fileDigests.map((f) => [f.path, f.sha256]),
    ...shippedAssets.map((a) => [a.path, a.sha256]),
  ]);

  const live = {
    schemaVersion: 1,
    generatedBy: "scripts/resolveProductionSourceUniverse.mjs",
    description:
      "Production source universe as of the current working tree, resolved from the exact bundler options that " +
      "produce dist/extension.js (esbuild.config.js) plus the contribution-asset and runtime-resource-copy rules " +
      "in scripts/lib/productionSourceScan.mjs. Regenerated every run; diffed against the immutable pre-gate " +
      "snapshot (workflow-production-source-pregate-v1.json), not authoritative on its own.",
    packageName: packageJson.name,
    packageVersion: packageJson.version,
    declaredMain: packageJson.main,
    entrypoint: buildOptions.entryPoints[0],
    outfile: buildOptions.outfile,
    bundlerName: "esbuild",
    bundlerVersion: require(path.join(repoRoot, "node_modules", "esbuild", "package.json")).version,
    typescriptVersion: require(path.join(repoRoot, "node_modules", "typescript", "package.json")).version,
    buildOptionsDigestSha256: buildOptionsDigest,
    lockfileSha256: fs.existsSync(lockfilePath) ? sha256OfFile(lockfilePath) : null,
    fileCount: fileDigests.length,
    files: fileDigests,
    shippedAssets,
  };

  fs.mkdirSync(INVENTORY_DIR, { recursive: true });
  fs.writeFileSync(LIVE_PATH, JSON.stringify(live, null, 2) + "\n", "utf8");

  // --- diff live against the immutable pre-gate snapshot, requiring
  // recorded evidence for every addition/removal --------------------------
  const liveMembers = new Set([...live.files.map((f) => f.path), ...live.shippedAssets.map((a) => a.path)]);

  if (!fs.existsSync(PREGATE_PATH)) {
    record(
      `No immutable pre-gate snapshot found at ${toRepoRelativePosix(PREGATE_PATH)}. Run ` +
        `"node scripts/generatePregateProductionSourceBaseline.mjs" once (against the commit that predates this ` +
        `plan's changes) to establish it, then commit the result. This snapshot is never regenerated by this script.`
    );
  } else {
    const pregate = JSON.parse(fs.readFileSync(PREGATE_PATH, "utf8"));
    const pregateMembers = new Set([
      ...(pregate.files || []).map((f) => f.path),
      ...(pregate.shippedAssets || []).map((a) => a.path),
    ]);
    const pregateDigestsByPath = new Map([
      ...(pregate.files || []).map((f) => [f.path, f.sha256]),
      ...(pregate.shippedAssets || []).map((a) => [a.path, a.sha256]),
    ]);

    const added = [...liveMembers].filter((p) => !pregateMembers.has(p)).sort((a, b) => a.localeCompare(b));
    const removed = [...pregateMembers].filter((p) => !liveMembers.has(p)).sort((a, b) => a.localeCompare(b));
    // A path present in both snapshots whose content changed is "modified" —
    // membership diffing alone silently absorbs in-place edits to
    // already-tracked production files (the exact gap an earlier
    // implementation review identified: stale baseline digests for
    // package.json and legacyAiActionSafetyGateV0.ts were never diffed or
    // required to carry evidence). The immutable pre-gate snapshot predates
    // canonical digesting and recorded raw checkout-byte digests (a mix of
    // CRLF-form and LF-form rows from the generating machine's checkout
    // profile), so the comparison goes through the tolerant matcher: a
    // pre-gate digest matching the live content under ANY single-EOL
    // representation means unchanged content, on every OS/checkout profile;
    // anything else is a genuine content change requiring an annotation.
    const modified = [...liveMembers]
      .filter((p) => pregateMembers.has(p))
      .filter((p) => !fileMatchesRecordedSha256(path.join(repoRoot, p), pregateDigestsByPath.get(p)))
      .sort((a, b) => a.localeCompare(b));

    const annotations = loadAnnotations(record);
    if ((added.length > 0 || removed.length > 0 || modified.length > 0) && annotations === null) {
      record(
        `Production source universe has drifted from the immutable pre-gate snapshot (${added.length} added, ` +
          `${removed.length} removed, ${modified.length} modified), but ${toRepoRelativePosix(ANNOTATIONS_PATH)} ` +
          `does not exist. Every addition, removal, or content change since the pre-gate snapshot requires a ` +
          `recorded annotation (cohort + rationale + owner + expiry cohort + content-digest evidence).`
      );
    } else if (annotations !== null) {
      // An annotation's evidence digest must match the digest this run
      // computed itself — a rationale written against older content is stale
      // evidence, not evidence.
      const requireFreshLiveEvidence = (key, p) => {
        const entry = annotations.get(key);
        if (!entry || typeof entry.evidence !== "object" || entry.evidence === null) {
          return;
        }
        const liveDigest = digestsByPath.get(p);
        if (SHA256_RE.test(entry.evidence.liveSha256 || "") && entry.evidence.liveSha256 !== liveDigest) {
          record(
            `Annotation ${key} carries stale evidence: its liveSha256 (${entry.evidence.liveSha256}) does not match ` +
              `the file's current digest (${liveDigest}). Re-review the change and update the annotation's evidence.`
          );
        }
      };
      for (const p of added) {
        if (!annotations.has(`added:${p}`)) {
          record(
            `${p} was added since the immutable pre-gate snapshot but has no "added" entry in ${toRepoRelativePosix(
              ANNOTATIONS_PATH
            )}.`
          );
        } else {
          requireFreshLiveEvidence(`added:${p}`, p);
        }
      }
      for (const p of removed) {
        if (!annotations.has(`removed:${p}`)) {
          record(
            `${p} was removed since the immutable pre-gate snapshot but has no "removed" entry in ${toRepoRelativePosix(
              ANNOTATIONS_PATH
            )}.`
          );
        } else {
          const entry = annotations.get(`removed:${p}`);
          const pregateDigest = pregateDigestsByPath.get(p);
          if (
            entry && entry.evidence && SHA256_RE.test(entry.evidence.pregateSha256 || "") &&
            entry.evidence.pregateSha256 !== pregateDigest
          ) {
            record(
              `Annotation removed:${p} carries evidence.pregateSha256 (${entry.evidence.pregateSha256}) that does not ` +
                `match the pre-gate snapshot's digest (${pregateDigest}).`
            );
          }
        }
      }
      for (const p of modified) {
        if (!annotations.has(`modified:${p}`)) {
          record(
            `${p} content changed since the immutable pre-gate snapshot (digest mismatch) but has no "modified" ` +
              `entry in ${toRepoRelativePosix(ANNOTATIONS_PATH)}.`
          );
        } else {
          requireFreshLiveEvidence(`modified:${p}`, p);
        }
      }
    }
  }

  if (generate) {
    if (failures.length > 0) {
      console.error(
        `✘ Refusing to (re)write ${toRepoRelativePosix(BASELINE_PATH)}: ${failures.length} check(s) above failed. ` +
          `Fix them (including any undocumented pre-gate drift) before regenerating the baseline.`
      );
      process.exitCode = 1;
      return;
    }
    fs.writeFileSync(BASELINE_PATH, JSON.stringify(live, null, 2) + "\n", "utf8");
    console.log(
      `✓ Wrote baseline with ${fileDigests.length} bundled source file(s) and ${shippedAssets.length} shipped ` +
        `asset(s) to ${toRepoRelativePosix(BASELINE_PATH)}`
    );
    return;
  }

  if (!fs.existsSync(BASELINE_PATH)) {
    record(
      `No baseline found at ${toRepoRelativePosix(BASELINE_PATH)}. Run with --generate once to establish it, then commit the result.`
    );
  } else {
    const baseline = JSON.parse(fs.readFileSync(BASELINE_PATH, "utf8"));
    const baselineFiles = new Set((baseline.files || []).map((f) => f.path));
    const baselineAssets = new Set((baseline.shippedAssets || []).map((a) => a.path));
    const liveFiles = new Set(sortedFiles);
    const liveAssets = new Set(shippedAssets.map((a) => a.path));

    const addedFiles = [...liveFiles].filter((f) => !baselineFiles.has(f));
    const removedFiles = [...baselineFiles].filter((f) => !liveFiles.has(f));
    const addedAssets = [...liveAssets].filter((f) => !baselineAssets.has(f));
    const removedAssets = [...baselineAssets].filter((f) => !liveAssets.has(f));

    // Membership diffing alone misses in-place content edits to a path the
    // baseline and live scan both already know about — a stale baseline
    // digest for an unchanged path set would previously pass silently
    // (the exact species of gap an implementation review found once for
    // taskCreationSeedHistoryV1.ts). Compare content digests for every path
    // present in both, using the same baseline/live digest maps already
    // computed for the pre-gate comparison above.
    const baselineDigestsByPath = new Map([
      ...(baseline.files || []).map((f) => [f.path, f.sha256]),
      ...(baseline.shippedAssets || []).map((a) => [a.path, a.sha256]),
    ]);
    const modifiedFromBaseline = [...liveFiles, ...liveAssets]
      .filter((p) => baselineFiles.has(p) || baselineAssets.has(p))
      .filter((p) => baselineDigestsByPath.get(p) !== digestsByPath.get(p))
      .sort((a, b) => a.localeCompare(b));

    if (
      addedFiles.length > 0 ||
      removedFiles.length > 0 ||
      addedAssets.length > 0 ||
      removedAssets.length > 0 ||
      modifiedFromBaseline.length > 0
    ) {
      record(
        `Production source universe drifted from the checked-in baseline. ` +
          `Files added: ${addedFiles.join(", ") || "(none)"}; removed: ${removedFiles.join(", ") || "(none)"}. ` +
          `Assets added: ${addedAssets.join(", ") || "(none)"}; removed: ${removedAssets.join(", ") || "(none)"}. ` +
          `Content changed (digest mismatch) for path(s) present in both: ${modifiedFromBaseline.join(", ") || "(none)"}. ` +
          `If this drift is intentional and annotated, re-run with --generate and commit the updated baseline.`
      );
    }
  }

  if (failures.length > 0) {
    console.error(`✘ resolveProductionSourceUniverse: ${failures.length} check(s) failed.`);
    process.exitCode = 1;
  } else {
    console.log(
      `✓ resolveProductionSourceUniverse: ${fileDigests.length} bundled source file(s) and ${shippedAssets.length} ` +
        `shipped asset(s) verified against the checked-in baseline and the immutable pre-gate snapshot.`
    );
  }
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
